"use client";

import React, { useState, useEffect, useRef, useCallback } from 'react';

// --- Types ---
type EffectType = 'particles' | 'gradient-blobs' | 'matrix-rain' | 'waves' | 'starfield';

interface EffectConfig {
  colorA: string;
  colorB: string;
  colorC: string;
  bgColor: string;
  density: number;
  speed: number;
  connectDistance: number;
}

// --- Palettes ---
const PALETTES = [
  { name: 'Deep Space', bg: '#0a0a1a', colors: ['#6366f1', '#8b5cf6', '#a78bfa'] },
  { name: 'Cyberpunk', bg: '#0d0221', colors: ['#ff006e', '#8338ec', '#3a86ff'] },
  { name: 'Ocean', bg: '#0c1445', colors: ['#00b4d8', '#0077b6', '#90e0ef'] },
  { name: 'Forest', bg: '#0a1a0a', colors: ['#22c55e', '#16a34a', '#86efac'] },
  { name: 'Sunset', bg: '#1a0a0a', colors: ['#f97316', '#ef4444', '#fbbf24'] },
  { name: 'Arctic', bg: '#f0f4ff', colors: ['#3b82f6', '#6366f1', '#93c5fd'] },
  { name: 'Midnight', bg: '#0f172a', colors: ['#38bdf8', '#818cf8', '#c084fc'] },
  { name: 'Ember', bg: '#1c0800', colors: ['#dc2626', '#f97316', '#fcd34d'] },
];

const EFFECT_META: Record<EffectType, { label: string; tagline: string }> = {
  'particles':      { label: 'Particle Network', tagline: 'Interactive connected nodes' },
  'gradient-blobs': { label: 'Gradient Blobs',   tagline: 'Animated mesh gradients (Pure CSS)' },
  'matrix-rain':    { label: 'Matrix Rain',       tagline: 'Falling code with mouse glow' },
  'waves':          { label: 'Wave Gradient',     tagline: 'Flowing animated waves' },
  'starfield':      { label: 'Starfield',         tagline: 'Parallax star movement' },
};

// ================================================================
// CODE GENERATORS — produce self-contained HTML+CSS+JS snippets
// ================================================================

function generateParticleCode(c: EffectConfig): string {
  return `<!-- Particle Network Background — Generated by DevToolsLabs.com -->
<div id="particle-bg" style="position:fixed;top:0;left:0;width:100%;height:100%;z-index:-1;background:${c.bgColor};">
  <canvas id="particle-canvas" style="display:block;width:100%;height:100%;"></canvas>
</div>
<script>
(function(){
  const canvas = document.getElementById('particle-canvas');
  const ctx = canvas.getContext('2d');
  let w, h, particles = [], mouse = {x:-1000,y:-1000};
  const COLORS = ['${c.colorA}','${c.colorB}','${c.colorC}'];
  const COUNT = ${c.density};
  const SPEED = ${c.speed};
  const CONNECT = ${c.connectDistance};

  function resize(){ w=canvas.width=canvas.offsetWidth; h=canvas.height=canvas.offsetHeight; }
  window.addEventListener('resize', resize); resize();
  canvas.addEventListener('mousemove', e=>{ const r=canvas.getBoundingClientRect(); mouse={x:e.clientX-r.left,y:e.clientY-r.top}; });
  canvas.addEventListener('mouseleave', ()=>{ mouse={x:-1000,y:-1000}; });

  for(let i=0;i<COUNT;i++) particles.push({
    x:Math.random()*w, y:Math.random()*h,
    vx:(Math.random()-0.5)*SPEED, vy:(Math.random()-0.5)*SPEED,
    r:Math.random()*2+1, color:COLORS[i%3]
  });

  function hexToRgb(hex){
    const r=parseInt(hex.slice(1,3),16), g=parseInt(hex.slice(3,5),16), b=parseInt(hex.slice(5,7),16);
    return r+','+g+','+b;
  }

  function draw(){
    ctx.clearRect(0,0,w,h);
    for(let i=0;i<particles.length;i++){
      const p=particles[i];
      p.x+=p.vx; p.y+=p.vy;
      if(p.x<0||p.x>w) p.vx*=-1;
      if(p.y<0||p.y>h) p.vy*=-1;
      // Mouse attraction
      const dx=mouse.x-p.x, dy=mouse.y-p.y, dist=Math.sqrt(dx*dx+dy*dy);
      if(dist<150){ p.x+=dx*0.01; p.y+=dy*0.01; }
      ctx.beginPath(); ctx.arc(p.x,p.y,p.r,0,Math.PI*2);
      ctx.fillStyle=p.color; ctx.fill();
      // Connections
      for(let j=i+1;j<particles.length;j++){
        const q=particles[j], ddx=p.x-q.x, ddy=p.y-q.y, d=Math.sqrt(ddx*ddx+ddy*ddy);
        if(d<CONNECT){
          ctx.beginPath(); ctx.moveTo(p.x,p.y); ctx.lineTo(q.x,q.y);
          ctx.strokeStyle='rgba('+hexToRgb(p.color)+','+(1-d/CONNECT)*0.4+')';
          ctx.lineWidth=0.6; ctx.stroke();
        }
      }
    }
    requestAnimationFrame(draw);
  }
  draw();
})();
</script>`;
}

function generateGradientBlobsCode(c: EffectConfig): string {
  return `<!-- Gradient Blobs Background — Generated by DevToolsLabs.com -->
<style>
  .gradient-bg {
    position: fixed; top: 0; left: 0; width: 100%; height: 100%; z-index: -1;
    background: ${c.bgColor};
    overflow: hidden;
  }
  .gradient-bg .blob {
    position: absolute;
    border-radius: 50%;
    filter: blur(80px);
    opacity: 0.6;
    animation: blobFloat 12s ease-in-out infinite alternate;
  }
  .gradient-bg .blob:nth-child(1) {
    width: 500px; height: 500px; background: ${c.colorA};
    top: -10%; left: 10%;
    animation-duration: 8s;
  }
  .gradient-bg .blob:nth-child(2) {
    width: 400px; height: 400px; background: ${c.colorB};
    top: 40%; right: 5%;
    animation-duration: 12s; animation-delay: -4s;
  }
  .gradient-bg .blob:nth-child(3) {
    width: 350px; height: 350px; background: ${c.colorC};
    bottom: -5%; left: 30%;
    animation-duration: 10s; animation-delay: -2s;
  }
  @keyframes blobFloat {
    0%   { transform: translate(0, 0) scale(1); }
    33%  { transform: translate(60px, -40px) scale(1.1); }
    66%  { transform: translate(-40px, 60px) scale(0.95); }
    100% { transform: translate(50px, 30px) scale(1.05); }
  }
</style>
<div class="gradient-bg">
  <div class="blob"></div>
  <div class="blob"></div>
  <div class="blob"></div>
</div>`;
}

function generateMatrixCode(c: EffectConfig): string {
  return `<!-- Matrix Rain Background — Generated by DevToolsLabs.com -->
<div id="matrix-bg" style="position:fixed;top:0;left:0;width:100%;height:100%;z-index:-1;background:${c.bgColor};">
  <canvas id="matrix-canvas" style="display:block;width:100%;height:100%;"></canvas>
</div>
<script>
(function(){
  const canvas = document.getElementById('matrix-canvas');
  const ctx = canvas.getContext('2d');
  let w, h, columns, drops;
  const CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZアイウエオカキクケコ0123456789@#$%^&*';
  const FONT = 14;
  const SPEED = ${c.speed};
  let mouse = {x:-1000, y:-1000};

  function resize(){
    w=canvas.width=canvas.offsetWidth; h=canvas.height=canvas.offsetHeight;
    columns=Math.ceil(w/FONT);
    drops=Array.from({length:columns},()=>Math.random()*-50);
  }
  window.addEventListener('resize',resize); resize();
  canvas.addEventListener('mousemove',e=>{const r=canvas.getBoundingClientRect();mouse={x:e.clientX-r.left,y:e.clientY-r.top};});

  function hexToRgb(hex){
    return [parseInt(hex.slice(1,3),16),parseInt(hex.slice(3,5),16),parseInt(hex.slice(5,7),16)];
  }
  const mainColor = hexToRgb('${c.colorA}');
  const glowColor = hexToRgb('${c.colorB}');
  const bgRgb = hexToRgb('${c.bgColor}');

  function draw(){
    ctx.fillStyle='rgba('+bgRgb[0]+','+bgRgb[1]+','+bgRgb[2]+',0.05)';
    ctx.fillRect(0,0,w,h);
    for(let i=0;i<columns;i++){
      const x=i*FONT, y=drops[i]*FONT;
      const ch=CHARS[Math.floor(Math.random()*CHARS.length)];
      const dx=x-mouse.x, dy=y-mouse.y, dist=Math.sqrt(dx*dx+dy*dy);
      const glow=dist<120?(1-dist/120):0;
      if(glow>0.1){
        ctx.font='bold '+(FONT+2)+'px monospace';
        ctx.fillStyle='rgba('+glowColor[0]+','+glowColor[1]+','+glowColor[2]+','+(0.9+glow*0.1)+')';
        ctx.shadowBlur=20*glow; ctx.shadowColor='${c.colorB}';
      } else {
        ctx.font=FONT+'px monospace';
        ctx.fillStyle='rgba('+mainColor[0]+','+mainColor[1]+','+mainColor[2]+','+(0.5+Math.random()*0.4)+')';
        ctx.shadowBlur=0;
      }
      ctx.fillText(ch,x,y); ctx.shadowBlur=0;
      if(y>h&&Math.random()>0.975) drops[i]=0;
      drops[i]+=SPEED*0.5;
    }
    requestAnimationFrame(draw);
  }
  ctx.fillStyle='rgb('+bgRgb[0]+','+bgRgb[1]+','+bgRgb[2]+')';
  ctx.fillRect(0,0,w,h);
  draw();
})();
</script>`;
}

function generateWavesCode(c: EffectConfig): string {
  return `<!-- Wave Gradient Background — Generated by DevToolsLabs.com -->
<div id="wave-bg" style="position:fixed;top:0;left:0;width:100%;height:100%;z-index:-1;background:${c.bgColor};">
  <canvas id="wave-canvas" style="display:block;width:100%;height:100%;"></canvas>
</div>
<script>
(function(){
  const canvas = document.getElementById('wave-canvas');
  const ctx = canvas.getContext('2d');
  let w, h, t=0;
  const SPEED = ${c.speed * 0.01};
  let mouse = {x:0.5, y:0.5};

  function resize(){ w=canvas.width=canvas.offsetWidth; h=canvas.height=canvas.offsetHeight; }
  window.addEventListener('resize',resize); resize();
  canvas.addEventListener('mousemove',e=>{const r=canvas.getBoundingClientRect();mouse={x:(e.clientX-r.left)/w,y:(e.clientY-r.top)/h};});

  function hexToRgba(hex,a){
    const r=parseInt(hex.slice(1,3),16),g=parseInt(hex.slice(3,5),16),b=parseInt(hex.slice(5,7),16);
    return 'rgba('+r+','+g+','+b+','+a+')';
  }

  const waves = [
    { color:'${c.colorA}', amp:50, freq:0.8, speed:1, yOff:0.6, opacity:0.4 },
    { color:'${c.colorB}', amp:40, freq:1.2, speed:1.3, yOff:0.7, opacity:0.35 },
    { color:'${c.colorC}', amp:30, freq:1.6, speed:0.8, yOff:0.8, opacity:0.3 },
    { color:'${c.colorA}', amp:25, freq:2.0, speed:1.5, yOff:0.85, opacity:0.25 },
  ];

  function draw(){
    ctx.clearRect(0,0,w,h);
    ctx.fillStyle='${c.bgColor}'; ctx.fillRect(0,0,w,h);
    t+=SPEED;
    const mouseInfluence = (mouse.x-0.5)*30;
    waves.forEach(wave=>{
      ctx.beginPath(); ctx.moveTo(0,h);
      for(let x=0;x<=w;x+=4){
        const nx=x/w;
        const y=h*wave.yOff+Math.sin(nx*Math.PI*wave.freq+t*wave.speed+mouseInfluence)*wave.amp
                            +Math.sin(nx*Math.PI*wave.freq*2+t*wave.speed*0.5)*wave.amp*0.3;
        ctx.lineTo(x,y);
      }
      ctx.lineTo(w,h); ctx.closePath();
      ctx.fillStyle=hexToRgba(wave.color,wave.opacity); ctx.fill();
    });
    requestAnimationFrame(draw);
  }
  draw();
})();
</script>`;
}

function generateStarfieldCode(c: EffectConfig): string {
  return `<!-- Starfield Background — Generated by DevToolsLabs.com -->
<div id="star-bg" style="position:fixed;top:0;left:0;width:100%;height:100%;z-index:-1;background:${c.bgColor};">
  <canvas id="star-canvas" style="display:block;width:100%;height:100%;"></canvas>
</div>
<script>
(function(){
  const canvas = document.getElementById('star-canvas');
  const ctx = canvas.getContext('2d');
  let w, h;
  const COUNT = ${c.density};
  const SPEED = ${c.speed};
  let mouse = {x:0.5, y:0.5};

  function resize(){ w=canvas.width=canvas.offsetWidth; h=canvas.height=canvas.offsetHeight; }
  window.addEventListener('resize',resize); resize();
  canvas.addEventListener('mousemove',e=>{const r=canvas.getBoundingClientRect();mouse={x:(e.clientX-r.left)/w,y:(e.clientY-r.top)/h};});

  function hexToRgb(hex){
    return [parseInt(hex.slice(1,3),16),parseInt(hex.slice(3,5),16),parseInt(hex.slice(5,7),16)];
  }

  const stars=[];
  for(let i=0;i<COUNT;i++){
    stars.push({
      x:Math.random()*2-1, y:Math.random()*2-1, z:Math.random(),
      color:hexToRgb(['${c.colorA}','${c.colorB}','${c.colorC}'][i%3])
    });
  }

  function draw(){
    ctx.fillStyle='${c.bgColor}'; ctx.fillRect(0,0,w,h);
    const cx=w/2, cy=h/2;
    const ox=(mouse.x-0.5)*100, oy=(mouse.y-0.5)*100;
    for(const s of stars){
      s.z-=0.002*SPEED;
      if(s.z<=0){ s.z=1; s.x=Math.random()*2-1; s.y=Math.random()*2-1; }
      const px=cx+(s.x/s.z)*300+ox/s.z;
      const py=cy+(s.y/s.z)*300+oy/s.z;
      const size=(1-s.z)*3;
      const alpha=(1-s.z)*0.8+0.2;
      if(px>0&&px<w&&py>0&&py<h){
        ctx.beginPath(); ctx.arc(px,py,size,0,Math.PI*2);
        ctx.fillStyle='rgba('+s.color[0]+','+s.color[1]+','+s.color[2]+','+alpha+')';
        ctx.fill();
        // Glow
        ctx.beginPath(); ctx.arc(px,py,size*3,0,Math.PI*2);
        ctx.fillStyle='rgba('+s.color[0]+','+s.color[1]+','+s.color[2]+','+(alpha*0.1)+')';
        ctx.fill();
      }
    }
    requestAnimationFrame(draw);
  }
  draw();
})();
</script>`;
}

// Map effect to generator
const CODE_GENERATORS: Record<EffectType, (c: EffectConfig) => string> = {
  'particles': generateParticleCode,
  'gradient-blobs': generateGradientBlobsCode,
  'matrix-rain': generateMatrixCode,
  'waves': generateWavesCode,
  'starfield': generateStarfieldCode,
};

// ================================================================
// CANVAS PREVIEW ENGINES (for live preview only)
// ================================================================

function usePreviewCanvas(
  canvasRef: React.RefObject<HTMLCanvasElement | null>,
  config: EffectConfig,
  effect: EffectType
) {
  const animRef = useRef<number>(0);
  const mouseRef = useRef({ x: -1000, y: -1000 });

  useEffect(() => {
    if (!canvasRef.current) return;
    const canvas = canvasRef.current;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    cancelAnimationFrame(animRef.current);

    const w = canvas.offsetWidth;
    const h = canvas.offsetHeight;
    canvas.width = w * 2;
    canvas.height = h * 2;
    ctx.scale(2, 2);

    const onMouseMove = (e: MouseEvent) => {
      const rect = canvas.getBoundingClientRect();
      mouseRef.current = { x: e.clientX - rect.left, y: e.clientY - rect.top };
    };
    const onMouseLeave = () => { mouseRef.current = { x: -1000, y: -1000 }; };
    canvas.addEventListener('mousemove', onMouseMove);
    canvas.addEventListener('mouseleave', onMouseLeave);

    const hexToRgb = (hex: string) => {
      const r = parseInt(hex.slice(1, 3), 16);
      const g = parseInt(hex.slice(3, 5), 16);
      const b = parseInt(hex.slice(5, 7), 16);
      return [r, g, b];
    };

    // ---- PARTICLES ----
    if (effect === 'particles') {
      const colors = [config.colorA, config.colorB, config.colorC];
      const particles = Array.from({ length: config.density }, (_, i) => ({
        x: Math.random() * w, y: Math.random() * h,
        vx: (Math.random() - 0.5) * config.speed * 0.5,
        vy: (Math.random() - 0.5) * config.speed * 0.5,
        r: Math.random() * 2 + 1,
        color: colors[i % 3],
      }));

      const draw = () => {
        ctx.clearRect(0, 0, w, h);
        const bgRgb = hexToRgb(config.bgColor);
        ctx.fillStyle = `rgb(${bgRgb[0]},${bgRgb[1]},${bgRgb[2]})`;
        ctx.fillRect(0, 0, w, h);
        const mouse = mouseRef.current;

        for (let i = 0; i < particles.length; i++) {
          const p = particles[i];
          p.x += p.vx; p.y += p.vy;
          if (p.x < 0 || p.x > w) p.vx *= -1;
          if (p.y < 0 || p.y > h) p.vy *= -1;
          const dx = mouse.x - p.x, dy = mouse.y - p.y;
          const dist = Math.sqrt(dx * dx + dy * dy);
          if (dist < 150) { p.x += dx * 0.01; p.y += dy * 0.01; }

          const rgb = hexToRgb(p.color);
          ctx.beginPath(); ctx.arc(p.x, p.y, p.r, 0, Math.PI * 2);
          ctx.fillStyle = p.color; ctx.fill();

          for (let j = i + 1; j < particles.length; j++) {
            const q = particles[j];
            const ddx = p.x - q.x, ddy = p.y - q.y;
            const d = Math.sqrt(ddx * ddx + ddy * ddy);
            if (d < config.connectDistance) {
              ctx.beginPath(); ctx.moveTo(p.x, p.y); ctx.lineTo(q.x, q.y);
              ctx.strokeStyle = `rgba(${rgb[0]},${rgb[1]},${rgb[2]},${(1 - d / config.connectDistance) * 0.4})`;
              ctx.lineWidth = 0.6; ctx.stroke();
            }
          }
        }
        animRef.current = requestAnimationFrame(draw);
      };
      draw();
    }

    // ---- MATRIX RAIN ----
    if (effect === 'matrix-rain') {
      const fontSize = 14;
      const cols = Math.ceil(w / fontSize);
      const drops = Array.from({ length: cols }, () => Math.random() * -50);
      const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZアイウエオカキクケコ0123456789@#$%^&*';
      const mainRgb = hexToRgb(config.colorA);
      const glowRgb = hexToRgb(config.colorB);
      const bgRgb = hexToRgb(config.bgColor);

      ctx.fillStyle = `rgb(${bgRgb[0]},${bgRgb[1]},${bgRgb[2]})`;
      ctx.fillRect(0, 0, w, h);

      const draw = () => {
        ctx.fillStyle = `rgba(${bgRgb[0]},${bgRgb[1]},${bgRgb[2]},0.05)`;
        ctx.fillRect(0, 0, w, h);
        const mouse = mouseRef.current;

        for (let i = 0; i < cols; i++) {
          const x = i * fontSize, y = drops[i] * fontSize;
          const ch = chars[Math.floor(Math.random() * chars.length)];
          const dx = x - mouse.x, dy = y - mouse.y;
          const dist = Math.sqrt(dx * dx + dy * dy);
          const glow = dist < 120 ? (1 - dist / 120) : 0;

          if (glow > 0.1) {
            ctx.font = `bold ${fontSize + 2}px monospace`;
            ctx.fillStyle = `rgba(${glowRgb[0]},${glowRgb[1]},${glowRgb[2]},${0.9 + glow * 0.1})`;
            ctx.shadowBlur = 20 * glow;
            ctx.shadowColor = config.colorB;
          } else {
            ctx.font = `${fontSize}px monospace`;
            ctx.fillStyle = `rgba(${mainRgb[0]},${mainRgb[1]},${mainRgb[2]},${0.5 + Math.random() * 0.4})`;
            ctx.shadowBlur = 0;
          }
          ctx.fillText(ch, x, y);
          ctx.shadowBlur = 0;
          if (y > h && Math.random() > 0.975) drops[i] = 0;
          drops[i] += config.speed * 0.5;
        }
        animRef.current = requestAnimationFrame(draw);
      };
      draw();
    }

    // ---- WAVES ----
    if (effect === 'waves') {
      let t = 0;
      const waves = [
        { color: config.colorA, amp: 50, freq: 0.8, speed: 1, yOff: 0.6, opacity: 0.4 },
        { color: config.colorB, amp: 40, freq: 1.2, speed: 1.3, yOff: 0.7, opacity: 0.35 },
        { color: config.colorC, amp: 30, freq: 1.6, speed: 0.8, yOff: 0.8, opacity: 0.3 },
        { color: config.colorA, amp: 25, freq: 2.0, speed: 1.5, yOff: 0.85, opacity: 0.25 },
      ];

      const draw = () => {
        ctx.clearRect(0, 0, w, h);
        ctx.fillStyle = config.bgColor;
        ctx.fillRect(0, 0, w, h);
        t += config.speed * 0.01;
        const mouseInfluence = ((mouseRef.current.x / w) - 0.5) * 30;

        for (const wave of waves) {
          const rgb = hexToRgb(wave.color);
          ctx.beginPath();
          ctx.moveTo(0, h);
          for (let x = 0; x <= w; x += 4) {
            const nx = x / w;
            const y = h * wave.yOff
              + Math.sin(nx * Math.PI * wave.freq + t * wave.speed + mouseInfluence) * wave.amp
              + Math.sin(nx * Math.PI * wave.freq * 2 + t * wave.speed * 0.5) * wave.amp * 0.3;
            ctx.lineTo(x, y);
          }
          ctx.lineTo(w, h);
          ctx.closePath();
          ctx.fillStyle = `rgba(${rgb[0]},${rgb[1]},${rgb[2]},${wave.opacity})`;
          ctx.fill();
        }
        animRef.current = requestAnimationFrame(draw);
      };
      draw();
    }

    // ---- STARFIELD ----
    if (effect === 'starfield') {
      const starColors = [config.colorA, config.colorB, config.colorC];
      const stars = Array.from({ length: config.density }, (_, i) => ({
        x: Math.random() * 2 - 1, y: Math.random() * 2 - 1, z: Math.random(),
        color: hexToRgb(starColors[i % 3]),
      }));

      const draw = () => {
        ctx.fillStyle = config.bgColor;
        ctx.fillRect(0, 0, w, h);
        const cx = w / 2, cy = h / 2;
        const mx = (mouseRef.current.x > -500 ? mouseRef.current.x / w : 0.5);
        const my = (mouseRef.current.y > -500 ? mouseRef.current.y / h : 0.5);
        const ox = (mx - 0.5) * 100, oy = (my - 0.5) * 100;

        for (const s of stars) {
          s.z -= 0.002 * config.speed;
          if (s.z <= 0) { s.z = 1; s.x = Math.random() * 2 - 1; s.y = Math.random() * 2 - 1; }
          const px = cx + (s.x / s.z) * 300 + ox / s.z;
          const py = cy + (s.y / s.z) * 300 + oy / s.z;
          const size = (1 - s.z) * 3;
          const alpha = (1 - s.z) * 0.8 + 0.2;
          if (px > 0 && px < w && py > 0 && py < h) {
            ctx.beginPath(); ctx.arc(px, py, size, 0, Math.PI * 2);
            ctx.fillStyle = `rgba(${s.color[0]},${s.color[1]},${s.color[2]},${alpha})`;
            ctx.fill();
            ctx.beginPath(); ctx.arc(px, py, size * 3, 0, Math.PI * 2);
            ctx.fillStyle = `rgba(${s.color[0]},${s.color[1]},${s.color[2]},${alpha * 0.1})`;
            ctx.fill();
          }
        }
        animRef.current = requestAnimationFrame(draw);
      };
      draw();
    }

    return () => {
      cancelAnimationFrame(animRef.current);
      canvas.removeEventListener('mousemove', onMouseMove);
      canvas.removeEventListener('mouseleave', onMouseLeave);
    };
  }, [effect, config, canvasRef]);
}

// ================================================================
// MAIN COMPONENT
// ================================================================

export default function CssBackgroundPatternGeneratorTool() {
  const [effect, setEffect] = useState<EffectType>('particles');
  const [config, setConfig] = useState<EffectConfig>({
    colorA: '#6366f1',
    colorB: '#8b5cf6',
    colorC: '#a78bfa',
    bgColor: '#0a0a1a',
    density: 60,
    speed: 1,
    connectDistance: 120,
  });

  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [copied, setCopied] = useState(false);
  const [codeVisible, setCodeVisible] = useState(false);

  // Generate the copyable code
  const generatedCode = CODE_GENERATORS[effect](config);

  // Preview: Canvas effects
  const isCanvasPreview = effect !== 'gradient-blobs';
  usePreviewCanvas(canvasRef, config, effect);

  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(generatedCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  }, [generatedCode]);

  const applyPalette = (p: typeof PALETTES[0]) => {
    setConfig(c => ({ ...c, colorA: p.colors[0], colorB: p.colors[1], colorC: p.colors[2], bgColor: p.bg }));
  };

  // Count lines in generated code
  const lineCount = generatedCode.split('\n').length;
  const charCount = generatedCode.length;

  return (
    <div className="flex flex-col gap-6">
      {/* ===== LIVE PREVIEW ===== */}
      <div className="w-full h-72 md:h-[460px] rounded-2xl border border-gray-200 shadow-lg relative overflow-hidden">
        {/* Canvas preview */}
        {isCanvasPreview && (
          <canvas ref={canvasRef} className="absolute inset-0 w-full h-full" style={{ display: 'block' }} />
        )}

        {/* Gradient blobs CSS preview */}
        {effect === 'gradient-blobs' && (
          <div className="absolute inset-0 overflow-hidden" style={{ background: config.bgColor }}>
            <div className="absolute rounded-full opacity-60 blur-[80px]" style={{ width: '50%', height: '50%', background: config.colorA, top: '-10%', left: '10%', animation: 'blobPreview1 8s ease-in-out infinite alternate' }} />
            <div className="absolute rounded-full opacity-50 blur-[80px]" style={{ width: '40%', height: '40%', background: config.colorB, top: '40%', right: '5%', animation: 'blobPreview2 12s ease-in-out infinite alternate' }} />
            <div className="absolute rounded-full opacity-40 blur-[60px]" style={{ width: '35%', height: '35%', background: config.colorC, bottom: '-5%', left: '30%', animation: 'blobPreview3 10s ease-in-out infinite alternate' }} />
          </div>
        )}

        {/* Interactive hint */}
        <div className="absolute bottom-4 left-4 bg-black/30 backdrop-blur-sm px-3 py-1.5 rounded-full">
          <span className="text-white/70 text-xs font-medium">
            {effect === 'gradient-blobs' ? 'Pure CSS — no JavaScript needed' : 'Move your mouse to interact'}
          </span>
        </div>

        {/* Badge showing code is copyable */}
        <div className="absolute top-4 right-4 bg-black/40 backdrop-blur-sm px-3 py-1.5 rounded-full flex items-center gap-1.5">
          <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-green-400">
            <polyline points="16 18 22 12 16 6"></polyline><polyline points="8 6 2 12 8 18"></polyline>
          </svg>
          <span className="text-white/80 text-[10px] font-semibold tracking-wide uppercase">Copy-Paste Ready</span>
        </div>
      </div>

      <style>{`
        @keyframes blobPreview1 { 0% { transform: translate(0,0) scale(1); } 100% { transform: translate(60px,-40px) scale(1.1); } }
        @keyframes blobPreview2 { 0% { transform: translate(0,0) scale(1); } 100% { transform: translate(-40px,60px) scale(0.95); } }
        @keyframes blobPreview3 { 0% { transform: translate(0,0) scale(1); } 100% { transform: translate(50px,30px) scale(1.05); } }
      `}</style>

      {/* ===== CONTROLS ===== */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left column */}
        <div className="lg:col-span-2 space-y-5">
          {/* Effect Selector */}
          <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-5">
            <h2 className="text-sm font-semibold text-gray-900 mb-3">Choose Effect</h2>
            <div className="grid grid-cols-2 sm:grid-cols-5 gap-2">
              {(Object.keys(EFFECT_META) as EffectType[]).map((key) => (
                <button
                  key={key}
                  onClick={() => setEffect(key)}
                  className={`px-3 py-3 rounded-xl border-2 transition-all text-center ${
                    effect === key
                      ? 'border-black bg-black text-white shadow-md'
                      : 'border-gray-200 bg-white text-gray-700 hover:border-gray-300 hover:bg-gray-50'
                  }`}
                >
                  <span className="text-sm font-semibold block">{EFFECT_META[key].label}</span>
                  <span className={`text-[10px] block mt-0.5 ${effect === key ? 'text-gray-300' : 'text-gray-400'}`}>{EFFECT_META[key].tagline}</span>
                </button>
              ))}
            </div>
          </div>

          {/* Palettes */}
          <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-5">
            <h2 className="text-sm font-semibold text-gray-900 mb-3">Color Palettes</h2>
            <div className="grid grid-cols-4 sm:grid-cols-8 gap-2">
              {PALETTES.map((palette) => (
                <button key={palette.name} onClick={() => applyPalette(palette)} className="group flex flex-col items-center gap-1 p-2 rounded-lg hover:bg-gray-50 transition-colors" title={palette.name}>
                  <div className="flex gap-0.5">
                    {palette.colors.map((c, i) => (
                      <div key={i} className="w-4 h-4 rounded-full border border-white shadow-sm" style={{ backgroundColor: c }} />
                    ))}
                  </div>
                  <span className="text-[10px] text-gray-500 font-medium group-hover:text-gray-700">{palette.name}</span>
                </button>
              ))}
            </div>
          </div>

          {/* Fine Controls */}
          <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-5">
            <h2 className="text-sm font-semibold text-gray-900 mb-4">Customize</h2>
            <div className="space-y-4">
              {/* Color pickers */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                {([
                  { label: 'Primary', key: 'colorA' as const },
                  { label: 'Secondary', key: 'colorB' as const },
                  { label: 'Accent', key: 'colorC' as const },
                  { label: 'Background', key: 'bgColor' as const },
                ]).map(({ label, key }) => (
                  <div key={key}>
                    <label className="block text-xs font-medium text-gray-500 mb-1">{label}</label>
                    <div className="flex items-center gap-1.5">
                      <input type="color" value={config[key]} onChange={e => setConfig(c => ({ ...c, [key]: e.target.value }))} className="w-8 h-8 p-0 border-0 rounded cursor-pointer" />
                      <input type="text" value={config[key]} onChange={e => setConfig(c => ({ ...c, [key]: e.target.value }))} className="flex-1 px-2 py-1.5 border border-gray-200 rounded-lg text-xs font-mono uppercase focus:ring-2 focus:ring-black focus:border-black outline-none w-full" />
                    </div>
                  </div>
                ))}
              </div>

              {/* Sliders */}
              {effect !== 'gradient-blobs' && (
                <>
                  <SliderControl label="Speed" value={config.speed} min={0.2} max={3} step={0.1} suffix="x" onChange={v => setConfig(c => ({ ...c, speed: v }))} />
                  {(effect === 'particles' || effect === 'starfield') && (
                    <SliderControl label="Count" value={config.density} min={20} max={150} step={5} suffix="" onChange={v => setConfig(c => ({ ...c, density: v }))} />
                  )}
                  {effect === 'particles' && (
                    <SliderControl label="Connect Distance" value={config.connectDistance} min={50} max={250} step={10} suffix="px" onChange={v => setConfig(c => ({ ...c, connectDistance: v }))} />
                  )}
                </>
              )}
            </div>
          </div>
        </div>

        {/* Right column — Code Output */}
        <div className="space-y-5">
          {/* Copy button + stats */}
          <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-5 space-y-3">
            <div className="flex items-center justify-between">
              <h2 className="text-sm font-semibold text-gray-900">Generated Code</h2>
              <div className="flex items-center gap-2 text-[10px] text-gray-400 font-mono">
                <span>{lineCount} lines</span>
                <span>·</span>
                <span>{(charCount / 1024).toFixed(1)} KB</span>
              </div>
            </div>

            <button
              onClick={handleCopy}
              className={`w-full py-3 text-sm font-semibold rounded-lg transition-all flex items-center justify-center gap-2 ${
                copied
                  ? 'bg-green-600 text-white'
                  : 'bg-black hover:bg-gray-800 text-white'
              }`}
            >
              {copied ? (
                <>
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg>
                  Copied to Clipboard!
                </>
              ) : (
                <>
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg>
                  Copy Code
                </>
              )}
            </button>

            <p className="text-[11px] text-gray-400 text-center leading-snug">
              {effect === 'gradient-blobs'
                ? 'Pure HTML + CSS. Paste into any webpage.'
                : 'Self-contained HTML + JS. Zero dependencies. Just paste it.'}
            </p>
          </div>

          {/* Toggle code view */}
          <div className="bg-gray-50 rounded-xl border border-gray-200 shadow-sm overflow-hidden">
            <button
              onClick={() => setCodeVisible(!codeVisible)}
              className="w-full px-4 py-3 flex items-center justify-between text-sm font-semibold text-gray-700 hover:bg-gray-100 transition-colors"
            >
              <span>Preview Code</span>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={`transition-transform ${codeVisible ? 'rotate-180' : ''}`}>
                <polyline points="6 9 12 15 18 9"></polyline>
              </svg>
            </button>
            {codeVisible && (
              <pre className="bg-gray-900 text-gray-100 font-mono text-[11px] p-4 overflow-x-auto whitespace-pre-wrap leading-relaxed max-h-[400px] overflow-y-auto">
                {generatedCode}
              </pre>
            )}
          </div>

          {/* Active colors */}
          <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-5">
            <h2 className="text-sm font-semibold text-gray-900 mb-3">Active Colors</h2>
            <div className="flex gap-2">
              {[config.colorA, config.colorB, config.colorC].map((c, i) => (
                <div key={i} className="flex-1 h-10 rounded-lg shadow-inner border border-gray-100" style={{ backgroundColor: c }} />
              ))}
            </div>
            <p className="text-[10px] text-gray-400 mt-2 font-mono text-center">
              {config.colorA} · {config.colorB} · {config.colorC}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

// ===== Reusable Slider =====
function SliderControl({ label, value, min, max, step, suffix, onChange }: {
  label: string; value: number; min: number; max: number; step: number; suffix: string;
  onChange: (v: number) => void;
}) {
  return (
    <div>
      <div className="flex justify-between items-center mb-1">
        <label className="text-xs font-medium text-gray-600">{label}</label>
        <span className="text-xs font-mono font-medium text-gray-400 bg-gray-100 px-2 py-0.5 rounded">{value}{suffix}</span>
      </div>
      <input
        type="range" min={min} max={max} step={step} value={value}
        onChange={e => onChange(parseFloat(e.target.value))}
        className="w-full h-1.5 bg-gray-200 rounded-lg appearance-none cursor-pointer accent-black"
      />
    </div>
  );
}
