"use client";

import React, { useState, useEffect, useRef, useCallback } from 'react';

// --- Types ---
type EffectType = 'particles' | 'gradient-blobs' | 'matrix-rain' | 'waves' | 'starfield' | 'liquid-aura' | 'flow-field' | 'isometric-grid' | 'aurora-borealis';
type PlacementType = 'page' | 'container' | 'selector';

interface EffectConfig {
  colorA: string;
  colorB: string;
  colorC: string;
  bgColor: string;
  density: number;
  speed: number;
  connectDistance: number;
  placement?: PlacementType;
  customSelector?: string;
}

// --- Integration Helpers ---
function getWrapperStyles(c: EffectConfig): string {
  const isPage = !c.placement || c.placement === 'page';
  return `position:${isPage ? 'fixed' : 'absolute'};top:0;left:0;width:100%;height:100%;z-index:-1;background:${c.bgColor};overflow:hidden;pointer-events:none;`;
}

function getInitScript(canvasId: string, c: EffectConfig): string {
  if (!c.placement || c.placement === 'page') return `const canvas = document.getElementById('${canvasId}');`;
  
  const target = c.placement === 'selector' ? `document.querySelector('${c.customSelector}')` : `document.currentScript.parentElement.closest('.elementor-section, .elementor-container, section, div')`;
  
  return `
  const canvas = document.getElementById('${canvasId}');
  const container = ${target};
  if (container) {
    container.style.position = 'relative';
    container.style.overflow = 'hidden';
    if (container.offsetWidth) {
      canvas.width = container.offsetWidth;
      canvas.height = container.offsetHeight;
    }
  }
  `;
}

// --- Elementor-Native Helpers ---
function getElementorClassName(effect: EffectType): string {
  return `dtl-${effect}`;
}

function getElementorCSS(effect: EffectType, c: EffectConfig): string {
  const isCSSOnly = effect === 'gradient-blobs';
  
  let css = `/* Elementor Custom CSS — Generated by DevToolsLabs.com */
/* Paste this into: Section → Advanced → Custom CSS */

selector {
  position: relative;
  overflow: hidden;
}

selector > .elementor-widget-wrap,
selector > .elementor-container,
selector > .elementor-column-wrap {
  position: relative;
  z-index: 1;
}`;

  if (isCSSOnly) {
    css += `

/* Animated Gradient Blobs (Pure CSS) */
selector::before,
selector::after {
  content: '';
  position: absolute;
  border-radius: 50%;
  filter: blur(80px);
  pointer-events: none;
  z-index: 0;
  animation: dtlBlobFloat 12s ease-in-out infinite alternate;
}

selector::before {
  width: 500px; height: 500px;
  background: ${c.colorA};
  opacity: 0.6;
  top: -10%; left: 10%;
  animation-duration: 8s;
}

selector::after {
  width: 400px; height: 400px;
  background: ${c.colorB};
  opacity: 0.5;
  top: 40%; right: 5%;
  animation-duration: 12s;
  animation-direction: alternate-reverse;
}

@keyframes dtlBlobFloat {
  0%   { transform: translate(0, 0) scale(1); }
  33%  { transform: translate(60px, -40px) scale(1.1); }
  66%  { transform: translate(-40px, 60px) scale(0.95); }
  100% { transform: translate(50px, 30px) scale(1.05); }
}`;
  }
  
  return css;
}

function getElementorJS(effect: EffectType, c: EffectConfig): string {
  const className = getElementorClassName(effect);
  // Build the inner drawing logic for each effect
  const drawLogic = getCanvasDrawLogic(effect, c);
  
  return `<!-- Site Script — Generated by DevToolsLabs.com -->
<!-- Paste ONCE into: WPCode plugin / Theme Header / Elementor → Custom Code -->
<script>
document.addEventListener('DOMContentLoaded', function() {
  document.querySelectorAll('.${className}').forEach(function(section, idx) {
    // Setup container
    section.style.position = 'relative';
    section.style.overflow = 'hidden';

    // Create canvas
    var wrapper = document.createElement('div');
    wrapper.style.cssText = 'position:absolute;top:0;left:0;width:100%;height:100%;z-index:0;pointer-events:none;';
    var canvas = document.createElement('canvas');
    canvas.style.cssText = 'display:block;width:100%;height:100%;';
    canvas.id = 'dtl-canvas-' + idx;
    wrapper.appendChild(canvas);
    section.insertBefore(wrapper, section.firstChild);

    // Ensure content is above
    Array.from(section.children).forEach(function(child) {
      if (child !== wrapper) child.style.position = child.style.position || 'relative';
    });

${drawLogic}
  });
});
</script>`;
}

function getCanvasDrawLogic(effect: EffectType, c: EffectConfig): string {
  if (effect === 'gradient-blobs') return '    // Pure CSS effect — no JS needed!';
  
  if (effect === 'particles') return `    // Particle Network
    var ctx = canvas.getContext('2d');
    var w, h, particles = [], mouse = {x:-1000,y:-1000};
    var COLORS = ['${c.colorA}','${c.colorB}','${c.colorC}'];
    var COUNT = ${c.density}, SPEED = ${c.speed}, CONNECT = ${c.connectDistance};

    function resize(){
      var rect = section.getBoundingClientRect();
      w = rect.width; h = rect.height;
      var dpr = window.devicePixelRatio || 1;
      canvas.width = w * dpr; canvas.height = h * dpr;
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    }
    window.addEventListener('resize', resize); resize();
    section.addEventListener('mousemove', function(e){ var r=section.getBoundingClientRect(); mouse={x:e.clientX-r.left,y:e.clientY-r.top}; });
    section.addEventListener('mouseleave', function(){ mouse={x:-1000,y:-1000}; });

    for(var i=0;i<COUNT;i++) particles.push({
      x:Math.random()*w, y:Math.random()*h,
      vx:(Math.random()-0.5)*SPEED, vy:(Math.random()-0.5)*SPEED,
      color:COLORS[i%3], r:1.5+Math.random()*2
    });

    (function draw(){
      ctx.clearRect(0,0,w,h);
      ctx.fillStyle='${c.bgColor}'; ctx.fillRect(0,0,w,h);
      for(var i=0;i<particles.length;i++){
        var p=particles[i];
        p.x+=p.vx; p.y+=p.vy;
        if(p.x<0||p.x>w) p.vx*=-1;
        if(p.y<0||p.y>h) p.vy*=-1;
        var dm=Math.hypot(p.x-mouse.x,p.y-mouse.y);
        if(dm<150){ p.x+=(p.x-mouse.x)*0.02; p.y+=(p.y-mouse.y)*0.02; }
        ctx.beginPath(); ctx.arc(p.x,p.y,p.r,0,Math.PI*2);
        ctx.fillStyle=p.color; ctx.fill();
        for(var j=i+1;j<particles.length;j++){
          var p2=particles[j], d=Math.hypot(p.x-p2.x,p.y-p2.y);
          if(d<CONNECT){ ctx.beginPath(); ctx.moveTo(p.x,p.y); ctx.lineTo(p2.x,p2.y);
            ctx.strokeStyle=p.color.replace(')',','+(1-d/CONNECT)*0.3+')').replace('rgb','rgba');
            ctx.lineWidth=0.5; ctx.stroke(); }
        }
      }
      requestAnimationFrame(draw);
    })();`;

  if (effect === 'matrix-rain') return `    // Matrix Rain
    var ctx = canvas.getContext('2d');
    var w, h, columns, drops;
    var CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZアイウエオカキクケコ0123456789@#$%^&*';
    var FONT = 14, SPEED = ${c.speed};
    var mouse = {x:-1000, y:-1000};
    function hexToRgb(hex){ return [parseInt(hex.slice(1,3),16),parseInt(hex.slice(3,5),16),parseInt(hex.slice(5,7),16)]; }
    var mainColor = hexToRgb('${c.colorA}'), glowColor = hexToRgb('${c.colorB}'), bgRgb = hexToRgb('${c.bgColor}');

    function resize(){
      var rect = section.getBoundingClientRect();
      w = rect.width; h = rect.height;
      var dpr = window.devicePixelRatio || 1;
      canvas.width = w * dpr; canvas.height = h * dpr;
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
      columns=Math.ceil(w/FONT);
      drops=Array.from({length:columns},function(){ return Math.random()*-50; });
    }
    window.addEventListener('resize', resize); resize();
    section.addEventListener('mousemove', function(e){ var r=section.getBoundingClientRect(); mouse={x:e.clientX-r.left,y:e.clientY-r.top}; });
    ctx.fillStyle='rgb('+bgRgb[0]+','+bgRgb[1]+','+bgRgb[2]+')'; ctx.fillRect(0,0,w,h);

    (function draw(){
      ctx.fillStyle='rgba('+bgRgb[0]+','+bgRgb[1]+','+bgRgb[2]+',0.05)'; ctx.fillRect(0,0,w,h);
      for(var i=0;i<columns;i++){
        var x=i*FONT, y=drops[i]*FONT;
        var ch=CHARS[Math.floor(Math.random()*CHARS.length)];
        var dx=x-mouse.x, dy=y-mouse.y, dist=Math.sqrt(dx*dx+dy*dy);
        var glow=dist<120?(1-dist/120):0;
        if(glow>0.1){ ctx.font='bold '+(FONT+2)+'px monospace'; ctx.fillStyle='rgba('+glowColor[0]+','+glowColor[1]+','+glowColor[2]+','+(0.9+glow*0.1)+')'; ctx.shadowBlur=20*glow; ctx.shadowColor='${c.colorB}'; }
        else { ctx.font=FONT+'px monospace'; ctx.fillStyle='rgba('+mainColor[0]+','+mainColor[1]+','+mainColor[2]+','+(0.5+Math.random()*0.4)+')'; ctx.shadowBlur=0; }
        ctx.fillText(ch,x,y); ctx.shadowBlur=0;
        if(y>h&&Math.random()>0.975) drops[i]=0;
        drops[i]+=SPEED*0.5;
      }
      requestAnimationFrame(draw);
    })();`;

  if (effect === 'waves') return `    // Wave Gradient
    var ctx = canvas.getContext('2d');
    var w, h, t=0, SPEED = ${c.speed * 0.01};
    var mouse = {x:0.5, y:0.5};
    function hexToRgba(hex,a){ var r=parseInt(hex.slice(1,3),16),g=parseInt(hex.slice(3,5),16),b=parseInt(hex.slice(5,7),16); return 'rgba('+r+','+g+','+b+','+a+')'; }
    function resize(){
      var rect = section.getBoundingClientRect();
      w = rect.width; h = rect.height;
      var dpr = window.devicePixelRatio || 1;
      canvas.width = w * dpr; canvas.height = h * dpr;
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    }
    window.addEventListener('resize', resize); resize();
    section.addEventListener('mousemove', function(e){ var r=section.getBoundingClientRect(); mouse={x:(e.clientX-r.left)/w,y:(e.clientY-r.top)/h}; });
    var waves = [
      { color:'${c.colorA}', amp:50, freq:0.8, speed:1, yOff:0.6, opacity:0.4 },
      { color:'${c.colorB}', amp:40, freq:1.2, speed:1.3, yOff:0.7, opacity:0.35 },
      { color:'${c.colorC}', amp:30, freq:1.6, speed:0.8, yOff:0.8, opacity:0.3 },
      { color:'${c.colorA}', amp:25, freq:2.0, speed:1.5, yOff:0.85, opacity:0.25 }
    ];
    (function draw(){
      ctx.clearRect(0,0,w,h); ctx.fillStyle='${c.bgColor}'; ctx.fillRect(0,0,w,h); t+=SPEED;
      var mouseInfluence = (mouse.x-0.5)*30;
      waves.forEach(function(wave){
        ctx.beginPath(); ctx.moveTo(0,h);
        for(var x=0;x<=w;x+=4){ var nx=x/w; var y=h*wave.yOff+Math.sin(nx*Math.PI*wave.freq+t*wave.speed+mouseInfluence)*wave.amp+Math.sin(nx*Math.PI*wave.freq*2+t*wave.speed*0.5)*wave.amp*0.3; ctx.lineTo(x,y); }
        ctx.lineTo(w,h); ctx.closePath(); ctx.fillStyle=hexToRgba(wave.color,wave.opacity); ctx.fill();
      });
      requestAnimationFrame(draw);
    })();`;

  if (effect === 'starfield') return `    // Starfield
    var ctx = canvas.getContext('2d');
    var w, h, COUNT = ${c.density}, SPEED = ${c.speed};
    var mouse = {x:0.5, y:0.5};
    function hexToRgb(hex){ return [parseInt(hex.slice(1,3),16),parseInt(hex.slice(3,5),16),parseInt(hex.slice(5,7),16)]; }
    function resize(){
      var rect = section.getBoundingClientRect();
      w = rect.width; h = rect.height;
      var dpr = window.devicePixelRatio || 1;
      canvas.width = w * dpr; canvas.height = h * dpr;
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    }
    window.addEventListener('resize', resize); resize();
    section.addEventListener('mousemove', function(e){ var r=section.getBoundingClientRect(); mouse={x:(e.clientX-r.left)/w,y:(e.clientY-r.top)/h}; });
    var stars=[];
    for(var i=0;i<COUNT;i++) stars.push({ x:Math.random()*2-1, y:Math.random()*2-1, z:Math.random(), color:hexToRgb(['${c.colorA}','${c.colorB}','${c.colorC}'][i%3]) });
    (function draw(){
      ctx.fillStyle='${c.bgColor}'; ctx.fillRect(0,0,w,h);
      var cx=w/2,cy=h/2,ox=(mouse.x-0.5)*100,oy=(mouse.y-0.5)*100;
      for(var i=0;i<stars.length;i++){
        var s=stars[i]; s.z-=0.002*SPEED;
        if(s.z<=0){ s.z=1; s.x=Math.random()*2-1; s.y=Math.random()*2-1; }
        var px=cx+(s.x/s.z)*300+ox/s.z, py=cy+(s.y/s.z)*300+oy/s.z;
        var size=(1-s.z)*3, alpha=(1-s.z)*0.8+0.2;
        if(px>0&&px<w&&py>0&&py<h){
          ctx.beginPath(); ctx.arc(px,py,size,0,Math.PI*2);
          ctx.fillStyle='rgba('+s.color[0]+','+s.color[1]+','+s.color[2]+','+alpha+')'; ctx.fill();
        }
      }
      requestAnimationFrame(draw);
    })();`;

  if (effect === 'liquid-aura') return `    // Liquid Aura
    var ctx = canvas.getContext('2d');
    var w, h, time = 0;
    var mouse = {x:0.5, y:0.5};
    function resize(){
      var rect = section.getBoundingClientRect();
      w = rect.width; h = rect.height;
      canvas.width = w * window.devicePixelRatio; canvas.height = h * window.devicePixelRatio;
      ctx.setTransform(window.devicePixelRatio, 0, 0, window.devicePixelRatio, 0, 0);
    }
    window.addEventListener('resize', resize); resize();
    section.addEventListener('mousemove', function(e){ mouse.x = e.clientX/w; mouse.y = e.clientY/h; });
    (function draw(){
      time += 0.005 * ${c.speed};
      ctx.fillStyle = '${c.bgColor}'; ctx.fillRect(0, 0, w, h);
      for(var i=0; i<3; i++){
        var x = w * (0.5 + Math.cos(time + i*2 + mouse.x) * 0.3);
        var y = h * (0.5 + Math.sin(time + i*3 + mouse.y) * 0.3);
        var rad = Math.max(w, h) * 0.8;
        var grad = ctx.createRadialGradient(x, y, 0, x, y, rad);
        var colors = ['${c.colorA}', '${c.colorB}', '${c.colorC}'];
        grad.addColorStop(0, colors[i] + 'aa'); grad.addColorStop(1, 'transparent');
        ctx.globalCompositeOperation = 'screen'; ctx.fillStyle = grad; ctx.fillRect(0, 0, w, h);
      }
      requestAnimationFrame(draw);
    })();`;

  if (effect === 'flow-field') return `    // Flow Field
    var ctx = canvas.getContext('2d');
    var w, h, flowParticles = [];
    var mouse = {x:-100, y:-100};
    function resize(){
      var rect = section.getBoundingClientRect();
      w = rect.width; h = rect.height;
      canvas.width = w * window.devicePixelRatio; canvas.height = h * window.devicePixelRatio;
      ctx.setTransform(window.devicePixelRatio, 0, 0, window.devicePixelRatio, 0, 0);
    }
    window.addEventListener('resize', resize); resize();
    section.addEventListener('mousemove', function(e){ var r=section.getBoundingClientRect(); mouse.x=e.clientX-r.left; mouse.y=e.clientY-r.top; });
    var colorArr = ['${c.colorA}','${c.colorB}','${c.colorC}'];
    for(var i=0; i<${c.density * 5}; i++){
      flowParticles.push({ x:Math.random()*w, y:Math.random()*h, vx:0, vy:0, color:colorArr[Math.floor(Math.random()*3)] });
    }
    (function draw(){
      ctx.fillStyle = '${c.bgColor}1a'; ctx.fillRect(0, 0, w, h);
      flowParticles.forEach(function(p){
        var angle = (Math.sin(p.x * 0.005) + Math.cos(p.y * 0.005)) * Math.PI * 2;
        var dist = Math.hypot(mouse.x - p.x, mouse.y - p.y);
        var finalAngle = dist < 200 ? Math.atan2(mouse.y - p.y, mouse.x - p.x) : angle;
        p.vx += Math.cos(finalAngle) * 0.02 * ${c.speed}; p.vy += Math.sin(finalAngle) * 0.02 * ${c.speed};
        p.x += p.vx; p.y += p.vy; p.vx *= 0.95; p.vy *= 0.95;
        if(p.x<0||p.x>w||p.y<0||p.y>h){ p.x=Math.random()*w; p.y=Math.random()*h; p.vx=0; p.vy=0; }
        ctx.strokeStyle = p.color; ctx.lineWidth = 1.5;
        ctx.beginPath(); ctx.moveTo(p.x, p.y); ctx.lineTo(p.x - p.vx * 2, p.y - p.vy * 2); ctx.stroke();
      });
      requestAnimationFrame(draw);
    })();`;

  if (effect === 'isometric-grid') return `    // Isometric Grid
    var ctx = canvas.getContext('2d');
    var w, h, mouse = {x:0, y:0};
    var size = 30;
    function resize(){
      var rect = section.getBoundingClientRect();
      w = rect.width; h = rect.height;
      canvas.width = w * window.devicePixelRatio; canvas.height = h * window.devicePixelRatio;
      ctx.setTransform(window.devicePixelRatio, 0, 0, window.devicePixelRatio, 0, 0);
    }
    window.addEventListener('resize', resize); resize();
    section.addEventListener('mousemove', function(e){ var r=section.getBoundingClientRect(); mouse.x=e.clientX-r.left; mouse.y=e.clientY-r.top; });
    (function draw(){
      ctx.fillStyle = '${c.bgColor}'; ctx.fillRect(0, 0, w, h);
      var cols = Math.ceil(w / size) + 2, rows = Math.ceil(h / size) + 2;
      for(var i=0; i<cols; i++) for(var j=0; j<rows; j++){
        var x = i * size, y = j * size;
        var dist = Math.hypot(mouse.x - x, mouse.y - y);
        var factor = Math.max(0, 1 - dist / 300);
        ctx.strokeStyle = factor > 0.5 ? '${c.colorA}' : '${c.colorB}44';
        ctx.lineWidth = 0.5 + factor * 2;
        ctx.beginPath();
        ctx.moveTo(x, y - factor * 20 * ${c.speed});
        ctx.lineTo(x + size/2, y + size/4 - factor * 20 * ${c.speed});
        ctx.lineTo(x, y + size/2 - factor * 20 * ${c.speed});
        ctx.lineTo(x - size/2, y + size/4 - factor * 20 * ${c.speed});
        ctx.closePath(); ctx.stroke();
      }
      requestAnimationFrame(draw);
    })();`;

  // aurora-borealis
  return `    // Aurora Borealis
    var ctx = canvas.getContext('2d');
    var w, h, time = 0;
    var mouse = {x:0.5, y:0.5};
    function resize(){
      var rect = section.getBoundingClientRect();
      w = rect.width; h = rect.height;
      canvas.width = w * window.devicePixelRatio; canvas.height = h * window.devicePixelRatio;
      ctx.setTransform(window.devicePixelRatio, 0, 0, window.devicePixelRatio, 0, 0);
    }
    window.addEventListener('resize', resize); resize();
    section.addEventListener('mousemove', function(e){ var r=section.getBoundingClientRect(); mouse.x=(e.clientX-r.left)/w; mouse.y=(e.clientY-r.top)/h; });
    var auroraColors = ['${c.colorA}','${c.colorB}','${c.colorC}'];
    function hexToRgb(hex){ return [parseInt(hex.slice(1,3),16),parseInt(hex.slice(3,5),16),parseInt(hex.slice(5,7),16)]; }
    (function draw(){
      ctx.fillStyle = '${c.bgColor}'; ctx.fillRect(0, 0, w, h); time += 0.01 * ${c.speed};
      for(var i=0; i<3; i++){
        ctx.beginPath(); ctx.moveTo(0, h);
        var rgb = hexToRgb(auroraColors[i]);
        for(var x=0; x<=w; x+=10){
          var nx = x/w, drift = Math.sin(nx * 3 + time + i) * 50;
          var pull = (1 - Math.abs(nx - mouse.x)) * 100 * (1-mouse.y);
          ctx.lineTo(x, h * 0.7 - i*80 + drift - pull);
        }
        ctx.lineTo(w, h);
        var grad = ctx.createLinearGradient(0, h*0.5, 0, h);
        grad.addColorStop(0, 'rgba('+rgb[0]+','+rgb[1]+','+rgb[2]+',0.4)'); grad.addColorStop(1, 'transparent');
        ctx.fillStyle = grad; ctx.fill();
      }
      requestAnimationFrame(draw);
    })();`;
}


// --- Palettes ---
const PALETTES = [
  { name: 'Deep Space', bg: '#0a0a1a', colors: ['#6366f1', '#8b5cf6', '#a78bfa'] },
  { name: 'Cyberpunk', bg: '#0d0221', colors: ['#ff006e', '#8338ec', '#3a86ff'] },
  { name: 'Ocean', bg: '#0c1445', colors: ['#00b4d8', '#0077b6', '#90e0ef'] },
  { name: 'Forest', bg: '#0a1a0a', colors: ['#22c55e', '#16a34a', '#86efac'] },
  { name: 'Sunset', bg: '#1a0a0a', colors: ['#f97316', '#ef4444', '#fbbf24'] },
  { name: 'Arctic', bg: '#f0f4ff', colors: ['#3b82f6', '#6366f1', '#93c5fd'] },
  { name: 'Midnight', bg: '#0f172a', colors: ['#38bdf8', '#818cf8', '#c084fc'] },
  { name: 'Ember', bg: '#1c0800', colors: ['#dc2626', '#f97316', '#fcd34d'] },
];

const EFFECT_META: Record<EffectType, { label: string; tagline: string }> = {
  'particles':       { label: 'Particle Network', tagline: 'Interactive connected nodes' },
  'liquid-aura':     { label: 'Liquid Aura',      tagline: 'Morphing mesh gradient' },
  'flow-field':      { label: 'Flow Field',       tagline: 'Kinetic neural swarm' },
  'isometric-grid':  { label: 'Isometric Grid',   tagline: '3D reactive elevations' },
  'aurora-borealis': { label: 'Aurora',           tagline: 'Flowing cosmic bands' },
  'matrix-rain':     { label: 'Matrix Rain',      tagline: 'Falling code with mouse glow' },
  'waves':           { label: 'Wave Gradient',    tagline: 'Flowing animated waves' },
  'starfield':       { label: 'Starfield',        tagline: 'Parallax star movement' },
  'gradient-blobs':  { label: 'Gradient Blobs',   tagline: 'Animated mesh (Pure CSS)' },
};

// ================================================================
// CODE GENERATORS — produce self-contained HTML+CSS+JS snippets
// ================================================================

function generateParticleCode(c: EffectConfig): string {
  const canvasId = 'canvas-' + Math.random().toString(36).slice(2, 7);
  return `<!-- Particle Network Background — Generated by DevToolsLabs.com -->
<div class="dtl-bg-wrapper" style="${getWrapperStyles(c)}">
  <canvas id="${canvasId}" style="display:block;width:100%;height:100%;"></canvas>
</div>
<script>
(function(){
  ${getInitScript(canvasId, c)}
  const ctx = canvas.getContext('2d');
  let w, h, particles = [], mouse = {x:-1000,y:-1000};
  const COLORS = ['${c.colorA}','${c.colorB}','${c.colorC}'];
  const COUNT = ${c.density};
  const SPEED = ${c.speed};
  const CONNECT = ${c.connectDistance};

  function resize(){ 
    w = window.innerWidth; h = window.innerHeight;
    const dpr = window.devicePixelRatio || 1;
    canvas.width = w * dpr; canvas.height = h * dpr;
    ctx.scale(dpr, dpr);
  }
  window.addEventListener('resize', resize); resize();
  canvas.addEventListener('mousemove', e=>{ const r=canvas.getBoundingClientRect(); mouse={x:e.clientX-r.left,y:e.clientY-r.top}; });
  canvas.addEventListener('mouseleave', ()=>{ mouse={x:-1000,y:-1000}; });

  for(let i=0;i<COUNT;i++) particles.push({
    x:Math.random()*w, y:Math.random()*h,
    vx:(Math.random()-0.5)*SPEED, vy:(Math.random()-0.5)*SPEED,
    r:Math.random()*2+1, color:COLORS[i%3]
  });

  function hexToRgb(hex){
    const r=parseInt(hex.slice(1,3),16), g=parseInt(hex.slice(3,5),16), b=parseInt(hex.slice(5,7),16);
    return r+','+g+','+b;
  }

  function draw(){
    ctx.clearRect(0,0,w,h);
    for(let i=0;i<particles.length;i++){
      const p=particles[i];
      p.x+=p.vx; p.y+=p.vy;
      if(p.x<0||p.x>w) p.vx*=-1;
      if(p.y<0||p.y>h) p.vy*=-1;
      // Mouse attraction
      const dx=mouse.x-p.x, dy=mouse.y-p.y, dist=Math.sqrt(dx*dx+dy*dy);
      if(dist<150){ p.x+=dx*0.01; p.y+=dy*0.01; }
      ctx.beginPath(); ctx.arc(p.x,p.y,p.r,0,Math.PI*2);
      ctx.fillStyle=p.color; ctx.fill();
      // Connections
      for(let j=i+1;j<particles.length;j++){
        const q=particles[j], ddx=p.x-q.x, ddy=p.y-q.y, d=Math.sqrt(ddx*ddx+ddy*ddy);
        if(d<CONNECT){
          ctx.beginPath(); ctx.moveTo(p.x,p.y); ctx.lineTo(q.x,q.y);
          ctx.strokeStyle='rgba('+hexToRgb(p.color)+','+(1-d/CONNECT)*0.4+')';
          ctx.lineWidth=0.6; ctx.stroke();
        }
      }
    }
    requestAnimationFrame(draw);
  }
  draw();
})();
</script>`;
}

function generateGradientBlobsCode(c: EffectConfig): string {
  return `<!-- Gradient Blobs Background — Generated by DevToolsLabs.com -->
<div class="dtl-bg-wrapper" style="${getWrapperStyles(c)}">
  <div class="blob" style="position:absolute;width:500px;height:500px;background:${c.colorA};filter:blur(80px);border-radius:50%;opacity:0.6;top:-10%;left:10%;animation:blobFloat 8s ease-in-out infinite alternate;"></div>
  <div class="blob" style="position:absolute;width:400px;height:400px;background:${c.colorB};filter:blur(80px);border-radius:50%;opacity:0.5;top:40%;right:5%;animation:blobFloat 12s ease-in-out infinite alternate-reverse;animation-delay:-4s;"></div>
  <div class="blob" style="position:absolute;width:350px;height:350px;background:${c.colorC};filter:blur(60px);border-radius:50%;opacity:0.4;bottom:-5%;left:30%;animation:blobFloat 10s ease-in-out infinite alternate;animation-delay:-2s;"></div>
</div>
<style>
@keyframes blobFloat {
  0%   { transform: translate(0, 0) scale(1); }
  33%  { transform: translate(60px, -40px) scale(1.1); }
  66%  { transform: translate(-40px, 60px) scale(0.95); }
  100% { transform: translate(50px, 30px) scale(1.05); }
}
</style>`;
}

function generateMatrixCode(c: EffectConfig): string {
  const canvasId = 'canvas-' + Math.random().toString(36).slice(2, 7);
  return `<!-- Matrix Rain Background — Generated by DevToolsLabs.com -->
<div class="dtl-bg-wrapper" style="${getWrapperStyles(c)}">
  <canvas id="${canvasId}" style="display:block;width:100%;height:100%;"></canvas>
</div>
<script>
(function(){
  ${getInitScript(canvasId, c)}
  const ctx = canvas.getContext('2d');
  let w, h, columns, drops;
  const CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZアイウエオカキクケコ0123456789@#$%^&*';
  const FONT = 14;
  const SPEED = ${c.speed};
  let mouse = {x:-1000, y:-1000};

  function resize(){
    w = window.innerWidth; h = window.innerHeight;
    const dpr = window.devicePixelRatio || 1;
    canvas.width = w * dpr; canvas.height = h * dpr;
    ctx.scale(dpr, dpr);
    columns=Math.ceil(w/FONT);
    drops=Array.from({length:columns},()=>Math.random()*-50);
  }
  window.addEventListener('resize',resize); resize();
  canvas.addEventListener('mousemove',e=>{const r=canvas.getBoundingClientRect();mouse={x:e.clientX-r.left,y:e.clientY-r.top};});

  function hexToRgb(hex){
    return [parseInt(hex.slice(1,3),16),parseInt(hex.slice(3,5),16),parseInt(hex.slice(5,7),16)];
  }
  const mainColor = hexToRgb('${c.colorA}');
  const glowColor = hexToRgb('${c.colorB}');
  const bgRgb = hexToRgb('${c.bgColor}');

  function draw(){
    ctx.fillStyle='rgba('+bgRgb[0]+','+bgRgb[1]+','+bgRgb[2]+',0.05)';
    ctx.fillRect(0,0,w,h);
    for(let i=0;i<columns;i++){
      const x=i*FONT, y=drops[i]*FONT;
      const ch=CHARS[Math.floor(Math.random()*CHARS.length)];
      const dx=x-mouse.x, dy=y-mouse.y, dist=Math.sqrt(dx*dx+dy*dy);
      const glow=dist<120?(1-dist/120):0;
      if(glow>0.1){
        ctx.font='bold '+(FONT+2)+'px monospace';
        ctx.fillStyle='rgba('+glowColor[0]+','+glowColor[1]+','+glowColor[2]+','+(0.9+glow*0.1)+')';
        ctx.shadowBlur=20*glow; ctx.shadowColor='${c.colorB}';
      } else {
        ctx.font=FONT+'px monospace';
        ctx.fillStyle='rgba('+mainColor[0]+','+mainColor[1]+','+mainColor[2]+','+(0.5+Math.random()*0.4)+')';
        ctx.shadowBlur=0;
      }
      ctx.fillText(ch,x,y); ctx.shadowBlur=0;
      if(y>h&&Math.random()>0.975) drops[i]=0;
      drops[i]+=SPEED*0.5;
    }
    requestAnimationFrame(draw);
  }
  ctx.fillStyle='rgb('+bgRgb[0]+','+bgRgb[1]+','+bgRgb[2]+')';
  ctx.fillRect(0,0,w,h);
  draw();
})();
</script>`;
}

function generateWavesCode(c: EffectConfig): string {
  const canvasId = 'canvas-' + Math.random().toString(36).slice(2, 7);
  return `<!-- Wave Gradient Background — Generated by DevToolsLabs.com -->
<div class="dtl-bg-wrapper" style="${getWrapperStyles(c)}">
  <canvas id="${canvasId}" style="display:block;width:100%;height:100%;"></canvas>
</div>
<script>
(function(){
  ${getInitScript(canvasId, c)}
  const ctx = canvas.getContext('2d');
  let w, h, t=0;
  const SPEED = ${c.speed * 0.01};
  let mouse = {x:0.5, y:0.5};

  function resize(){ 
    w = window.innerWidth; h = window.innerHeight;
    const dpr = window.devicePixelRatio || 1;
    canvas.width = w * dpr; canvas.height = h * dpr;
    ctx.scale(dpr, dpr);
  }
  window.addEventListener('resize',resize); resize();
  canvas.addEventListener('mousemove',e=>{const r=canvas.getBoundingClientRect();mouse={x:(e.clientX-r.left)/w,y:(e.clientY-r.top)/h};});

  function hexToRgba(hex,a){
    const r=parseInt(hex.slice(1,3),16),g=parseInt(hex.slice(3,5),16),b=parseInt(hex.slice(5,7),16);
    return 'rgba('+r+','+g+','+b+','+a+')';
  }

  const waves = [
    { color:'${c.colorA}', amp:50, freq:0.8, speed:1, yOff:0.6, opacity:0.4 },
    { color:'${c.colorB}', amp:40, freq:1.2, speed:1.3, yOff:0.7, opacity:0.35 },
    { color:'${c.colorC}', amp:30, freq:1.6, speed:0.8, yOff:0.8, opacity:0.3 },
    { color:'${c.colorA}', amp:25, freq:2.0, speed:1.5, yOff:0.85, opacity:0.25 },
  ];

  function draw(){
    ctx.clearRect(0,0,w,h);
    ctx.fillStyle='${c.bgColor}'; ctx.fillRect(0,0,w,h);
    t+=SPEED;
    const mouseInfluence = (mouse.x-0.5)*30;
    waves.forEach(wave=>{
      ctx.beginPath(); ctx.moveTo(0,h);
      for(let x=0;x<=w;x+=4){
        const nx=x/w;
        const y=h*wave.yOff+Math.sin(nx*Math.PI*wave.freq+t*wave.speed+mouseInfluence)*wave.amp
                            +Math.sin(nx*Math.PI*wave.freq*2+t*wave.speed*0.5)*wave.amp*0.3;
        ctx.lineTo(x,y);
      }
      ctx.lineTo(w,h); ctx.closePath();
      ctx.fillStyle=hexToRgba(wave.color,wave.opacity); ctx.fill();
    });
    requestAnimationFrame(draw);
  }
  draw();
})();
</script>`;
}

function generateStarfieldCode(c: EffectConfig): string {
  const canvasId = 'canvas-' + Math.random().toString(36).slice(2, 7);
  return `<!-- Starfield Background — Generated by DevToolsLabs.com -->
<div class="dtl-bg-wrapper" style="${getWrapperStyles(c)}">
  <canvas id="${canvasId}" style="display:block;width:100%;height:100%;"></canvas>
</div>
<script>
(function(){
  ${getInitScript(canvasId, c)}
  const ctx = canvas.getContext('2d');
  let w, h;
  const COUNT = ${c.density};
  const SPEED = ${c.speed};
  let mouse = {x:0.5, y:0.5};

  function resize(){ 
    w = window.innerWidth; h = window.innerHeight;
    const dpr = window.devicePixelRatio || 1;
    canvas.width = w * dpr; canvas.height = h * dpr;
    ctx.scale(dpr, dpr);
  }
  window.addEventListener('resize',resize); resize();
  canvas.addEventListener('mousemove',e=>{const r=canvas.getBoundingClientRect();mouse={x:(e.clientX-r.left)/w,y:(e.clientY-r.top)/h};});

  function hexToRgb(hex){
    return [parseInt(hex.slice(1,3),16),parseInt(hex.slice(3,5),16),parseInt(hex.slice(5,7),16)];
  }

  const stars=[];
  for(let i=0;i<COUNT;i++){
    stars.push({
      x:Math.random()*2-1, y:Math.random()*2-1, z:Math.random(),
      color:hexToRgb(['${c.colorA}','${c.colorB}','${c.colorC}'][i%3])
    });
  }

  function draw(){
    ctx.fillStyle='${c.bgColor}'; ctx.fillRect(0,0,w,h);
    const cx=w/2, cy=h/2;
    const ox=(mouse.x-0.5)*100, oy=(mouse.y-0.5)*100;
    for(const s of stars){
      s.z-=0.002*SPEED;
      if(s.z<=0){ s.z=1; s.x=Math.random()*2-1; s.y=Math.random()*2-1; }
      const px=cx+(s.x/s.z)*300+ox/s.z;
      const py=cy+(s.y/s.z)*300+oy/s.z;
      const size=(1-s.z)*3;
      const alpha=(1-s.z)*0.8+0.2;
      if(px>0&&px<w&&py>0&&py<h){
        ctx.beginPath(); ctx.arc(px,py,size,0,Math.PI*2);
        ctx.fillStyle='rgba('+s.color[0]+','+s.color[1]+','+s.color[2]+','+alpha+')';
        ctx.fill();
        ctx.beginPath(); ctx.arc(px,py,size*3,0,Math.PI*2);
        ctx.fillStyle='rgba('+s.color[0]+','+s.color[1]+','+s.color[2]+','+(alpha*0.1)+')';
        ctx.fill();
      }
    }
    requestAnimationFrame(draw);
  }
  draw();
})();
</script>`;
}

function generateLiquidAuraCode(c: EffectConfig): string {
  const canvasId = 'canvas-' + Math.random().toString(36).slice(2, 7);
  return `<!-- Liquid Aura Background — Generated by DevToolsLabs.com -->
<div class="dtl-bg-wrapper" style="${getWrapperStyles(c)}">
  <canvas id="${canvasId}" style="display:block;width:100%;height:100%;"></canvas>
</div>
<script>
(function(){
  ${getInitScript(canvasId, c)}
  const ctx = canvas.getContext('2d');
  let w, h, time = 0;
  let mouse = {x:0.5, y:0.5};

  function resize(){
    w = window.innerWidth; h = window.innerHeight;
    canvas.width = w * window.devicePixelRatio;
    canvas.height = h * window.devicePixelRatio;
    ctx.scale(window.devicePixelRatio, window.devicePixelRatio);
  }
  window.addEventListener('resize', resize); resize();
  window.addEventListener('mousemove', e => { mouse.x = e.clientX/w; mouse.y = e.clientY/h; });

  function draw(){
    time += 0.005 * ${c.speed};
    ctx.fillStyle = '${c.bgColor}';
    ctx.fillRect(0, 0, w, h);
    
    for(let i=0; i<3; i++){
      const x = w * (0.5 + Math.cos(time + i*2 + mouse.x) * 0.3);
      const y = h * (0.5 + Math.sin(time + i*3 + mouse.y) * 0.3);
      const rad = Math.max(w, h) * 0.8;
      const grad = ctx.createRadialGradient(x, y, 0, x, y, rad);
      const colors = ['${c.colorA}', '${c.colorB}', '${c.colorC}'];
      grad.addColorStop(0, colors[i] + 'aa');
      grad.addColorStop(1, 'transparent');
      ctx.globalCompositeOperation = 'screen';
      ctx.fillStyle = grad;
      ctx.fillRect(0, 0, w, h);
    }
    requestAnimationFrame(draw);
  }
  draw();
})();
</script>`;
}

function generateFlowFieldCode(c: EffectConfig): string {
  const canvasId = 'canvas-' + Math.random().toString(36).slice(2, 7);
  return `<!-- Flow Field Background — Generated by DevToolsLabs.com -->
<div class="dtl-bg-wrapper" style="${getWrapperStyles(c)}">
  <canvas id="${canvasId}" style="display:block;width:100%;height:100%;"></canvas>
</div>
<script>
(function(){
  ${getInitScript(canvasId, c)}
  const ctx = canvas.getContext('2d');
  let w, h, particles = [];
  let mouse = {x:-100, y:-100};

  function resize(){
    w = window.innerWidth; h = window.innerHeight;
    canvas.width = w * window.devicePixelRatio;
    canvas.height = h * window.devicePixelRatio;
    ctx.scale(window.devicePixelRatio, window.devicePixelRatio);
  }
  window.addEventListener('resize', resize); resize();
  window.addEventListener('mousemove', e => { mouse.x = e.clientX; mouse.y = e.clientY; });

  class Particle {
    constructor(){ this.init(); }
    init(){
      this.x = Math.random() * w; this.y = Math.random() * h;
      this.vx = 0; this.vy = 0; this.acc = 0.02; this.len = 2;
      this.color = ['${c.colorA}', '${c.colorB}', '${c.colorC}'][Math.floor(Math.random()*3)];
    }
    draw(){
      const angle = (Math.sin(this.x * 0.005) + Math.cos(this.y * 0.005)) * Math.PI * 2;
      const mAngle = Math.atan2(mouse.y - this.y, mouse.x - this.x);
      const dist = Math.hypot(mouse.x - this.x, mouse.y - this.y);
      const finalAngle = dist < 200 ? mAngle : angle;
      
      this.vx += Math.cos(finalAngle) * this.acc * ${c.speed};
      this.vy += Math.sin(finalAngle) * this.acc * ${c.speed};
      this.x += this.vx; this.y += this.vy;
      this.vx *= 0.95; this.vy *= 0.95;

      if(this.x<0||this.x>w||this.y<0||this.y>h) this.init();
      
      ctx.strokeStyle = this.color; ctx.lineWidth = 1.5;
      ctx.beginPath(); ctx.moveTo(this.x, this.y);
      ctx.lineTo(this.x - this.vx * this.len, this.y - this.vy * this.len);
      ctx.stroke();
    }
  }

  for(let i=0; i<${c.density * 5}; i++) particles.push(new Particle());

  function draw(){
    ctx.fillStyle = 'rgba(0,0,0,0.1)';
    ctx.fillStyle = '${c.bgColor}1a';
    ctx.fillRect(0, 0, w, h);
    particles.forEach(p => p.draw());
    requestAnimationFrame(draw);
  }
  draw();
})();
</script>`;
}

function generateIsometricCode(c: EffectConfig): string {
  const canvasId = 'canvas-' + Math.random().toString(36).slice(2, 7);
  return `<!-- Isometric Grid Background — Generated by DevToolsLabs.com -->
<div class="dtl-bg-wrapper" style="${getWrapperStyles(c)}">
  <canvas id="${canvasId}" style="display:block;width:100%;height:100%;"></canvas>
</div>
<script>
(function(){
  ${getInitScript(canvasId, c)}
  const ctx = canvas.getContext('2d');
  let w, h, mouse = {x:0, y:0};
  const size = 30;

  function resize(){
    w = window.innerWidth; h = window.innerHeight;
    canvas.width = w * window.devicePixelRatio;
    canvas.height = h * window.devicePixelRatio;
    ctx.scale(window.devicePixelRatio, window.devicePixelRatio);
  }
  window.addEventListener('resize', resize); resize();
  window.addEventListener('mousemove', e => { mouse.x = e.clientX; mouse.y = e.clientY; });

  function draw(){
    ctx.fillStyle = '${c.bgColor}';
    ctx.fillRect(0, 0, w, h);
    const cols = Math.ceil(w / size) + 2;
    const rows = Math.ceil(h / size) + 2;

    for(let i=0; i<cols; i++){
      for(let j=0; j<rows; j++){
        const x = i * size; const y = j * size;
        const dx = mouse.x - x; const dy = mouse.y - y;
        const dist = Math.hypot(dx, dy);
        const factor = Math.max(0, 1 - dist / 300);
        
        ctx.strokeStyle = factor > 0.5 ? '${c.colorA}' : '${c.colorB}44';
        ctx.lineWidth = 0.5 + factor * 2;
        
        ctx.beginPath();
        ctx.moveTo(x, y - factor * 20 * ${c.speed});
        ctx.lineTo(x + size/2, y + size/4 - factor * 20 * ${c.speed});
        ctx.lineTo(x, y + size/2 - factor * 20 * ${c.speed});
        ctx.lineTo(x - size/2, y + size/4 - factor * 20 * ${c.speed});
        ctx.closePath();
        ctx.stroke();
      }
    }
    requestAnimationFrame(draw);
  }
  draw();
})();
</script>`;
}

function generateAuroraCode(c: EffectConfig): string {
  const canvasId = 'canvas-' + Math.random().toString(36).slice(2, 7);
  return `<!-- Aurora Background — Generated by DevToolsLabs.com -->
<div class="dtl-bg-wrapper" style="${getWrapperStyles(c)}">
  <canvas id="${canvasId}" style="display:block;width:100%;height:100%;"></canvas>
</div>
<script>
(function(){
  ${getInitScript(canvasId, c)}
  const ctx = canvas.getContext('2d');
  let w, h, time = 0;
  let mouse = {x:0.5, y:0.5};

  function resize(){
    w = window.innerWidth; h = window.innerHeight;
    canvas.width = w * window.devicePixelRatio;
    canvas.height = h * window.devicePixelRatio;
    ctx.scale(window.devicePixelRatio, window.devicePixelRatio);
  }
  window.addEventListener('resize', resize); resize();
  window.addEventListener('mousemove', e => { mouse.x = e.clientX/w; mouse.y = e.clientY/h; });

  function draw(){
    ctx.fillStyle = '${c.bgColor}';
    ctx.fillRect(0, 0, w, h);
    time += 0.01 * ${c.speed};

    for(let i=0; i<3; i++){
      ctx.beginPath();
      ctx.moveTo(0, h);
      const colors = ['${c.colorA}', '${c.colorB}', '${c.colorC}'];
      for(let x=0; x<=w; x+=10){
        const nx = x/w;
        const drift = Math.sin(nx * 3 + time + i) * 50;
        const pull = (1 - Math.abs(nx - mouse.x)) * 100 * (1-mouse.y);
        const y = h * 0.7 - i*80 + drift - pull;
        ctx.lineTo(x, y);
      }
      ctx.lineTo(w, h);
      const grad = ctx.createLinearGradient(0, h*0.5, 0, h);
      grad.addColorStop(0, colors[i] + '66');
      grad.addColorStop(1, 'transparent');
      ctx.fillStyle = grad;
      ctx.fill();
    }
    requestAnimationFrame(draw);
  }
  draw();
})();
</script>`;
}

// Map effect to generator
const CODE_GENERATORS: Record<EffectType, (c: EffectConfig) => string> = {
  'particles': generateParticleCode,
  'gradient-blobs': generateGradientBlobsCode,
  'matrix-rain': generateMatrixCode,
  'waves': generateWavesCode,
  'starfield': generateStarfieldCode,
  'liquid-aura': generateLiquidAuraCode,
  'flow-field': generateFlowFieldCode,
  'isometric-grid': generateIsometricCode,
  'aurora-borealis': generateAuroraCode,
};

// ================================================================
// CANVAS PREVIEW ENGINES (for live preview only)
// ================================================================

function usePreviewCanvas(
  canvasRef: React.RefObject<HTMLCanvasElement | null>,
  config: EffectConfig,
  effect: EffectType
) {
  const animRef = useRef<number>(0);
  const mouseRef = useRef({ x: -1000, y: -1000 });

  useEffect(() => {
    if (!canvasRef.current) return;
    const canvas = canvasRef.current;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    cancelAnimationFrame(animRef.current);

    const w = canvas.offsetWidth;
    const h = canvas.offsetHeight;
    const dpr = window.devicePixelRatio || 1;
    canvas.width = w * dpr;
    canvas.height = h * dpr;
    ctx.scale(dpr, dpr);

    const onMouseMove = (e: MouseEvent) => {
      const rect = canvas.getBoundingClientRect();
      mouseRef.current = { x: e.clientX - rect.left, y: e.clientY - rect.top };
    };
    const onMouseLeave = () => { mouseRef.current = { x: -1000, y: -1000 }; };
    canvas.addEventListener('mousemove', onMouseMove);
    canvas.addEventListener('mouseleave', onMouseLeave);

    const hexToRgb = (hex: string) => {
      const r = parseInt(hex.slice(1, 3), 16);
      const g = parseInt(hex.slice(3, 5), 16);
      const b = parseInt(hex.slice(5, 7), 16);
      return [r, g, b];
    };

    // ---- PARTICLES ----
    if (effect === 'particles') {
      const colors = [config.colorA, config.colorB, config.colorC];
      const particles = Array.from({ length: config.density }, (_, i) => ({
        x: Math.random() * w, y: Math.random() * h,
        vx: (Math.random() - 0.5) * config.speed * 0.5,
        vy: (Math.random() - 0.5) * config.speed * 0.5,
        r: Math.random() * 2 + 1,
        color: colors[i % 3],
      }));

      const draw = () => {
        ctx.clearRect(0, 0, w, h);
        const bgRgb = hexToRgb(config.bgColor);
        ctx.fillStyle = `rgb(${bgRgb[0]},${bgRgb[1]},${bgRgb[2]})`;
        ctx.fillRect(0, 0, w, h);
        const mouse = mouseRef.current;

        for (let i = 0; i < particles.length; i++) {
          const p = particles[i];
          p.x += p.vx; p.y += p.vy;
          if (p.x < 0 || p.x > w) p.vx *= -1;
          if (p.y < 0 || p.y > h) p.vy *= -1;
          const dx = mouse.x - p.x, dy = mouse.y - p.y;
          const dist = Math.sqrt(dx * dx + dy * dy);
          if (dist < 150) { p.x += dx * 0.01; p.y += dy * 0.01; }

          const rgb = hexToRgb(p.color);
          ctx.beginPath(); ctx.arc(p.x, p.y, p.r, 0, Math.PI * 2);
          ctx.fillStyle = p.color; ctx.fill();

          for (let j = i + 1; j < particles.length; j++) {
            const q = particles[j];
            const ddx = p.x - q.x, ddy = p.y - q.y;
            const d = Math.sqrt(ddx * ddx + ddy * ddy);
            if (d < config.connectDistance) {
              ctx.beginPath(); ctx.moveTo(p.x, p.y); ctx.lineTo(q.x, q.y);
              ctx.strokeStyle = `rgba(${rgb[0]},${rgb[1]},${rgb[2]},${(1 - d / config.connectDistance) * 0.4})`;
              ctx.lineWidth = 0.6; ctx.stroke();
            }
          }
        }
        animRef.current = requestAnimationFrame(draw);
      };
      draw();
    }

    // ---- MATRIX RAIN ----
    if (effect === 'matrix-rain') {
      const fontSize = 14;
      const cols = Math.ceil(w / fontSize);
      const drops = Array.from({ length: cols }, () => Math.random() * -50);
      const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZアイウエオカキクケコ0123456789@#$%^&*';
      const mainRgb = hexToRgb(config.colorA);
      const glowRgb = hexToRgb(config.colorB);
      const bgRgb = hexToRgb(config.bgColor);

      ctx.fillStyle = `rgb(${bgRgb[0]},${bgRgb[1]},${bgRgb[2]})`;
      ctx.fillRect(0, 0, w, h);

      const draw = () => {
        ctx.fillStyle = `rgba(${bgRgb[0]},${bgRgb[1]},${bgRgb[2]},0.05)`;
        ctx.fillRect(0, 0, w, h);
        const mouse = mouseRef.current;

        for (let i = 0; i < cols; i++) {
          const x = i * fontSize, y = drops[i] * fontSize;
          const ch = chars[Math.floor(Math.random() * chars.length)];
          const dx = x - mouse.x, dy = y - mouse.y;
          const dist = Math.sqrt(dx * dx + dy * dy);
          const glow = dist < 120 ? (1 - dist / 120) : 0;

          if (glow > 0.1) {
            ctx.font = `bold ${fontSize + 2}px monospace`;
            ctx.fillStyle = `rgba(${glowRgb[0]},${glowRgb[1]},${glowRgb[2]},${0.9 + glow * 0.1})`;
            ctx.shadowBlur = 20 * glow;
            ctx.shadowColor = config.colorB;
          } else {
            ctx.font = `${fontSize}px monospace`;
            ctx.fillStyle = `rgba(${mainRgb[0]},${mainRgb[1]},${mainRgb[2]},${0.5 + Math.random() * 0.4})`;
            ctx.shadowBlur = 0;
          }
          ctx.fillText(ch, x, y);
          ctx.shadowBlur = 0;
          if (y > h && Math.random() > 0.975) drops[i] = 0;
          drops[i] += config.speed * 0.5;
        }
        animRef.current = requestAnimationFrame(draw);
      };
      draw();
    }

    // ---- WAVES ----
    if (effect === 'waves') {
      let t = 0;
      const waves = [
        { color: config.colorA, amp: 50, freq: 0.8, speed: 1, yOff: 0.6, opacity: 0.4 },
        { color: config.colorB, amp: 40, freq: 1.2, speed: 1.3, yOff: 0.7, opacity: 0.35 },
        { color: config.colorC, amp: 30, freq: 1.6, speed: 0.8, yOff: 0.8, opacity: 0.3 },
        { color: config.colorA, amp: 25, freq: 2.0, speed: 1.5, yOff: 0.85, opacity: 0.25 },
      ];

      const draw = () => {
        ctx.clearRect(0, 0, w, h);
        ctx.fillStyle = config.bgColor;
        ctx.fillRect(0, 0, w, h);
        t += config.speed * 0.01;
        const mouseInfluence = ((mouseRef.current.x / w) - 0.5) * 30;

        for (const wave of waves) {
          const rgb = hexToRgb(wave.color);
          ctx.beginPath();
          ctx.moveTo(0, h);
          for (let x = 0; x <= w; x += 4) {
            const nx = x / w;
            const y = h * wave.yOff
              + Math.sin(nx * Math.PI * wave.freq + t * wave.speed + mouseInfluence) * wave.amp
              + Math.sin(nx * Math.PI * wave.freq * 2 + t * wave.speed * 0.5) * wave.amp * 0.3;
            ctx.lineTo(x, y);
          }
          ctx.lineTo(w, h);
          ctx.closePath();
          ctx.fillStyle = `rgba(${rgb[0]},${rgb[1]},${rgb[2]},${wave.opacity})`;
          ctx.fill();
        }
        animRef.current = requestAnimationFrame(draw);
      };
      draw();
    }

    // ---- STARFIELD ----
    if (effect === 'starfield') {
      const starColors = [config.colorA, config.colorB, config.colorC];
      const stars = Array.from({ length: config.density }, (_, i) => ({
        x: Math.random() * 2 - 1, y: Math.random() * 2 - 1, z: Math.random(),
        color: hexToRgb(starColors[i % 3]),
      }));

      const draw = () => {
        ctx.fillStyle = config.bgColor;
        ctx.fillRect(0, 0, w, h);
        const cx = w / 2, cy = h / 2;
        const mx = (mouseRef.current.x > -500 ? mouseRef.current.x / w : 0.5);
        const my = (mouseRef.current.y > -500 ? mouseRef.current.y / h : 0.5);
        const ox = (mx - 0.5) * 100, oy = (my - 0.5) * 100;

        for (const s of stars) {
          s.z -= 0.002 * config.speed;
          if (s.z <= 0) { s.z = 1; s.x = Math.random() * 2 - 1; s.y = Math.random() * 2 - 1; }
          const px = cx + (s.x / s.z) * 300 + ox / s.z;
          const py = cy + (s.y / s.z) * 300 + oy / s.z;
          const size = (1 - s.z) * 3;
          const alpha = (1 - s.z) * 0.8 + 0.2;
          if (px > 0 && px < w && py > 0 && py < h) {
            ctx.beginPath(); ctx.arc(px, py, size, 0, Math.PI * 2);
            ctx.fillStyle = `rgba(${s.color[0]},${s.color[1]},${s.color[2]},${alpha})`;
            ctx.fill();
            ctx.beginPath(); ctx.arc(px, py, size * 3, 0, Math.PI * 2);
            ctx.fillStyle = `rgba(${s.color[0]},${s.color[1]},${s.color[2]},${alpha * 0.1})`;
            ctx.fill();
          }
        }
        animRef.current = requestAnimationFrame(draw);
      };
      draw();
    }

    // ---- LIQUID AURA ----
    if (effect === 'liquid-aura') {
      let time = 0;
      const draw = () => {
        if (!ctx) return;
        time += 0.005 * config.speed;
        ctx.fillStyle = config.bgColor;
        ctx.fillRect(0, 0, w, h);
        const mx = mouseRef.current.x > -500 ? mouseRef.current.x / w : 0.5;
        const my = mouseRef.current.y > -500 ? mouseRef.current.y / h : 0.5;

        for (let i = 0; i < 3; i++) {
          const x = w * (0.5 + Math.cos(time + i * 2 + mx) * 0.3);
          const y = h * (0.5 + Math.sin(time + i * 3 + my) * 0.3);
          const rad = Math.max(w, h) * 0.8;
          const grad = ctx.createRadialGradient(x, y, 0, x, y, rad);
          const colors = [config.colorA, config.colorB, config.colorC];
          const rgb = hexToRgb(colors[i]);
          grad.addColorStop(0, `rgba(${rgb[0]},${rgb[1]},${rgb[2]},0.6)`);
          grad.addColorStop(1, 'transparent');
          ctx.globalCompositeOperation = 'screen';
          ctx.fillStyle = grad;
          ctx.fillRect(0, 0, w, h);
        }
        ctx.globalCompositeOperation = 'source-over';
        animRef.current = requestAnimationFrame(draw);
      };
      draw();
    }

    // ---- FLOW FIELD ----
    if (effect === 'flow-field') {
      class Particle {
        x = Math.random() * w; y = Math.random() * h;
        vx = 0; vy = 0; acc = 0.02; len = 2;
        color = [config.colorA, config.colorB, config.colorC][Math.floor(Math.random() * 3)];
        init() {
          this.x = Math.random() * w; this.y = Math.random() * h;
          this.vx = 0; this.vy = 0;
        }
        draw() {
          if (!ctx) return;
          const angle = (Math.sin(this.x * 0.005) + Math.cos(this.y * 0.005)) * Math.PI * 2;
          const mouse = mouseRef.current;
          const mAngle = Math.atan2(mouse.y - this.y, mouse.x - this.x);
          const dist = Math.hypot(mouse.x - this.x, mouse.y - this.y);
          const finalAngle = dist < 200 ? mAngle : angle;
          this.vx += Math.cos(finalAngle) * this.acc * config.speed;
          this.vy += Math.sin(finalAngle) * this.acc * config.speed;
          this.x += this.vx; this.y += this.vy;
          this.vx *= 0.95; this.vy *= 0.95;
          if (this.x < 0 || this.x > w || this.y < 0 || this.y > h) this.init();
          ctx.strokeStyle = this.color; ctx.lineWidth = 1.5;
          ctx.beginPath(); ctx.moveTo(this.x, this.y);
          ctx.lineTo(this.x - this.vx * this.len, this.y - this.vy * this.len);
          ctx.stroke();
        }
      }
      const particles = Array.from({ length: config.density * 5 }, () => new Particle());
      const draw = () => {
        if (!ctx) return;
        ctx.fillStyle = config.bgColor + '1a';
        ctx.fillRect(0, 0, w, h);
        particles.forEach(p => p.draw());
        animRef.current = requestAnimationFrame(draw);
      };
      draw();
    }

    // ---- ISOMETRIC GRID ----
    if (effect === 'isometric-grid') {
      const size = 30;
      const draw = () => {
        if (!ctx) return;
        ctx.fillStyle = config.bgColor;
        ctx.fillRect(0, 0, w, h);
        const cols = Math.ceil(w / size) + 2;
        const rows = Math.ceil(h / size) + 2;
        const mouse = mouseRef.current;

        for (let i = 0; i < cols; i++) {
          for (let j = 0; j < rows; j++) {
            const x = i * size; const y = j * size;
            const dx = mouse.x - x; const dy = mouse.y - y;
            const dist = Math.hypot(dx, dy);
            const factor = Math.max(0, 1 - dist / 300);
            ctx.strokeStyle = factor > 0.5 ? config.colorA : config.colorB + '44';
            ctx.lineWidth = 0.5 + factor * 2;
            ctx.beginPath();
            ctx.moveTo(x, y - factor * 20 * config.speed);
            ctx.lineTo(x + size / 2, y + size / 4 - factor * 20 * config.speed);
            ctx.lineTo(x, y + size / 2 - factor * 20 * config.speed);
            ctx.lineTo(x - size / 2, y + size / 4 - factor * 20 * config.speed);
            ctx.closePath();
            ctx.stroke();
          }
        }
        animRef.current = requestAnimationFrame(draw);
      };
      draw();
    }

    // ---- AURORA ----
    if (effect === 'aurora-borealis') {
      let time = 0;
      const draw = () => {
        if (!ctx) return;
        ctx.fillStyle = config.bgColor;
        ctx.fillRect(0, 0, w, h);
        time += 0.01 * config.speed;
        const mx = mouseRef.current.x / w;
        const my = mouseRef.current.y / h;

        for (let i = 0; i < 3; i++) {
          ctx.beginPath();
          ctx.moveTo(0, h);
          const colors = [config.colorA, config.colorB, config.colorC];
          const rgb = hexToRgb(colors[i]);
          for (let x = 0; x <= w; x += 10) {
            const nx = x / w;
            const drift = Math.sin(nx * 3 + time + i) * 50;
            const pull = (1 - Math.abs(nx - (mx || 0.5))) * 100 * (1 - (my || 0.5));
            const y = h * 0.7 - i * 80 + drift - pull;
            ctx.lineTo(x, y);
          }
          ctx.lineTo(w, h);
          const grad = ctx.createLinearGradient(0, h * 0.5, 0, h);
          grad.addColorStop(0, `rgba(${rgb[0]},${rgb[1]},${rgb[2]},0.4)`);
          grad.addColorStop(1, 'transparent');
          ctx.fillStyle = grad;
          ctx.fill();
        }
        animRef.current = requestAnimationFrame(draw);
      };
      draw();
    }

    return () => {
      cancelAnimationFrame(animRef.current);
      canvas.removeEventListener('mousemove', onMouseMove);
      canvas.removeEventListener('mouseleave', onMouseLeave);
    };
  }, [effect, config, canvasRef]);
}

// ================================================================
// MAIN COMPONENT
// ================================================================

export default function CssBackgroundPatternGeneratorTool() {
  const [effect, setEffect] = useState<EffectType>('particles');
  const [placement, setPlacement] = useState<PlacementType>('page');
  const [customSelector, setCustomSelector] = useState('.elementor-section');
  const [config, setConfig] = useState<EffectConfig>({
    colorA: '#6366f1',
    colorB: '#8b5cf6',
    colorC: '#a78bfa',
    bgColor: '#0a0a1a',
    density: 60,
    speed: 1,
    connectDistance: 120,
  });

  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [copied, setCopied] = useState(false);
  const [copiedStep, setCopiedStep] = useState<string | null>(null);
  const [codeVisible, setCodeVisible] = useState(false);

  // Generate the copyable code
  const generatedCode = CODE_GENERATORS[effect]({ ...config, placement, customSelector });

  // Elementor-specific outputs
  const elementorClassName = getElementorClassName(effect);
  const elementorCSS = getElementorCSS(effect, config);
  const elementorJS = getElementorJS(effect, config);
  const isCSSOnlyEffect = effect === 'gradient-blobs';

  // Preview: Canvas effects
  const isCanvasPreview = effect !== 'gradient-blobs';
  usePreviewCanvas(canvasRef, config, effect);

  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(generatedCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  }, [generatedCode]);

  const handleStepCopy = useCallback((text: string, stepId: string) => {
    navigator.clipboard.writeText(text);
    setCopiedStep(stepId);
    setTimeout(() => setCopiedStep(null), 2500);
  }, []);

  const applyPalette = (p: typeof PALETTES[0]) => {
    setConfig(c => ({ ...c, colorA: p.colors[0], colorB: p.colors[1], colorC: p.colors[2], bgColor: p.bg }));
  };

  // Count lines in generated code
  const lineCount = generatedCode.split('\n').length;
  const charCount = generatedCode.length;

  return (
    <div className="flex flex-col gap-6">
      {/* ===== LIVE PREVIEW ===== */}
      <div className="w-full h-72 md:h-[460px] rounded-2xl border border-gray-200 shadow-lg relative overflow-hidden">
        {/* Canvas preview */}
        {isCanvasPreview && (
          <canvas ref={canvasRef} className="absolute inset-0 w-full h-full" style={{ display: 'block' }} />
        )}

        {/* Gradient blobs CSS preview */}
        {effect === 'gradient-blobs' && (
          <div className="absolute inset-0 overflow-hidden" style={{ background: config.bgColor }}>
            <div className="absolute rounded-full opacity-60 blur-[80px]" style={{ width: '50%', height: '50%', background: config.colorA, top: '-10%', left: '10%', animation: 'blobPreview1 8s ease-in-out infinite alternate' }} />
            <div className="absolute rounded-full opacity-50 blur-[80px]" style={{ width: '40%', height: '40%', background: config.colorB, top: '40%', right: '5%', animation: 'blobPreview2 12s ease-in-out infinite alternate' }} />
            <div className="absolute rounded-full opacity-40 blur-[60px]" style={{ width: '35%', height: '35%', background: config.colorC, bottom: '-5%', left: '30%', animation: 'blobPreview3 10s ease-in-out infinite alternate' }} />
          </div>
        )}

        {/* Interactive hint */}
        <div className="absolute bottom-4 left-4 bg-black/30 backdrop-blur-sm px-3 py-1.5 rounded-full">
          <span className="text-white/70 text-xs font-medium">
            {effect === 'gradient-blobs' ? 'Pure CSS — no JavaScript needed' : 'Move your mouse to interact'}
          </span>
        </div>

        {/* Badge showing code is copyable */}
        <div className="absolute top-4 right-4 bg-black/40 backdrop-blur-sm px-3 py-1.5 rounded-full flex items-center gap-1.5">
          <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-green-400">
            <polyline points="16 18 22 12 16 6"></polyline><polyline points="8 6 2 12 8 18"></polyline>
          </svg>
          <span className="text-white/80 text-[10px] font-semibold tracking-wide uppercase">Copy-Paste Ready</span>
        </div>
      </div>

      <style>{`
        @keyframes blobPreview1 { 0% { transform: translate(0,0) scale(1); } 100% { transform: translate(60px,-40px) scale(1.1); } }
        @keyframes blobPreview2 { 0% { transform: translate(0,0) scale(1); } 100% { transform: translate(-40px,60px) scale(0.95); } }
        @keyframes blobPreview3 { 0% { transform: translate(0,0) scale(1); } 100% { transform: translate(50px,30px) scale(1.05); } }
      `}</style>

      {/* ===== CONTROLS ===== */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left column */}
        <div className="lg:col-span-2 space-y-5">
          {/* Effect Selector */}
          <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-5">
            <h2 className="text-sm font-semibold text-gray-900 mb-3">Choose Effect</h2>
            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 lg:grid-cols-5 gap-2">
              {(Object.keys(EFFECT_META) as EffectType[]).map((key) => (
                <button
                  suppressHydrationWarning
                  key={key}
                  onClick={() => setEffect(key)}
                  className={`px-3 py-3 rounded-xl border-2 transition-all text-center flex flex-col items-center justify-center ${
                    effect === key
                      ? 'border-black bg-black text-white shadow-md'
                      : 'border-gray-200 bg-white text-gray-700 hover:border-gray-300 hover:bg-gray-50'
                  }`}
                >
                  <span className="text-xs font-bold block">{EFFECT_META[key].label}</span>
                  <span className={`text-[9px] block mt-0.5 leading-tight ${effect === key ? 'text-gray-300' : 'text-gray-400'}`}>{EFFECT_META[key].tagline}</span>
                </button>
              ))}
            </div>
          </div>

          {/* Palettes */}
          <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-5">
            <h2 className="text-sm font-semibold text-gray-900 mb-3">Color Palettes</h2>
            <div className="grid grid-cols-4 sm:grid-cols-8 gap-2">
              {PALETTES.map((palette) => (
                <button suppressHydrationWarning key={palette.name} onClick={() => applyPalette(palette)} className="group flex flex-col items-center gap-1 p-2 rounded-lg hover:bg-gray-50 transition-colors" title={palette.name}>
                  <div className="flex gap-0.5">
                    {palette.colors.map((c, i) => (
                      <div key={i} className="w-4 h-4 rounded-full border border-white shadow-sm" style={{ backgroundColor: c }} />
                    ))}
                  </div>
                  <span className="text-[10px] text-gray-500 font-medium group-hover:text-gray-700 text-center">{palette.name}</span>
                </button>
              ))}
            </div>
          </div>

          {/* Integration Settings (NEW) */}
          <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-5">
            <div className="flex items-center gap-2 mb-4">
              <h2 className="text-sm font-semibold text-gray-900">Integration Settings</h2>
              <span className="bg-black text-[10px] text-white px-1.5 py-0.5 rounded font-bold uppercase tracking-wider">Pro</span>
            </div>
            
            <div className="space-y-4">
              <div>
                <label className="block text-[11px] font-semibold text-gray-400 uppercase tracking-wider mb-2 text-center">Placement Mode</label>
                <div className="flex p-1 bg-gray-100 rounded-xl">
                  {[
                    { id: 'page', label: 'Full Page', sub: 'Site-wide', icon: 'M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z' },
                    { id: 'container', label: 'Elementor', sub: 'Fill Section', icon: 'M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z' },
                    { id: 'selector', label: 'Custom', sub: 'CSS ID/Class', icon: 'M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z' }
                  ].map((opt) => (
                    <button
                      suppressHydrationWarning
                      key={opt.id}
                      onClick={() => setPlacement(opt.id as PlacementType)}
                      className={`flex-1 flex flex-col items-center gap-0.5 py-2.5 px-1 rounded-lg transition-all ${
                        placement === opt.id 
                          ? 'bg-white text-black shadow-sm ring-1 ring-black/5' 
                          : 'text-gray-500 hover:text-gray-700'
                      }`}
                    >
                      <svg className="w-4 h-4 mb-0.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <path d={opt.icon} />
                      </svg>
                      <span className="text-[10px] font-bold">{opt.label}</span>
                      <span className="text-[8px] opacity-60 font-medium uppercase tracking-tighter">{opt.sub}</span>
                    </button>
                  ))}
                </div>
              </div>

              {placement === 'page' && (
                <div className="p-3 bg-gray-50 border border-gray-100 rounded-lg animate-in fade-in zoom-in-95 duration-300">
                  <p className="text-[11px] text-gray-600 leading-relaxed text-center">
                    Applies to your <strong>entire website</strong> background.
                  </p>
                </div>
              )}

              {placement === 'container' && (
                <div className="p-3 bg-green-50 border border-green-100 rounded-lg animate-in fade-in zoom-in-95 duration-300">
                  <p className="text-[11px] text-green-800 leading-relaxed">
                    <strong>3-Step Setup:</strong> Add a CSS class to your section, paste Custom CSS, and add a one-time script. Works on <strong>any section or widget</strong> — see the guide on the right →
                  </p>
                </div>
              )}

              {placement === 'selector' && (
                <div className="p-3 bg-gray-50 border border-gray-200 rounded-lg animate-in fade-in zoom-in-95 duration-300">
                  <label className="block text-[10px] font-bold text-gray-400 uppercase mb-1.5">Target CSS Selector</label>
                  <input 
                    suppressHydrationWarning
                    type="text" 
                    value={customSelector}
                    onChange={(e) => setCustomSelector(e.target.value)}
                    placeholder=".my-custom-class"
                    className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm font-mono focus:ring-2 focus:ring-black focus:border-black outline-none bg-white"
                  />
                  <p className="text-[9px] text-gray-500 mt-2 leading-tight text-center">
                    Target a specific <strong>#ID</strong> or <strong>.Class</strong> on your site.
                  </p>
                </div>
              )}
            </div>
          </div>

          {/* Fine Controls */}
          <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-5">
            <h2 className="text-sm font-semibold text-gray-900 mb-4">Customize</h2>
            <div className="space-y-4">
              {/* Color pickers */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                {([
                  { label: 'Primary', key: 'colorA' as const },
                  { label: 'Secondary', key: 'colorB' as const },
                  { label: 'Accent', key: 'colorC' as const },
                  { label: 'Background', key: 'bgColor' as const },
                ]).map(({ label, key }) => (
                  <div key={key}>
                    <label className="block text-xs font-medium text-gray-500 mb-1">{label}</label>
                    <div className="flex items-center gap-1.5">
                      <input suppressHydrationWarning type="color" value={config[key]} onChange={e => setConfig(c => ({ ...c, [key]: e.target.value }))} className="w-8 h-8 p-0 border-0 rounded cursor-pointer" />
                      <input suppressHydrationWarning type="text" value={config[key]} onChange={e => setConfig(c => ({ ...c, [key]: e.target.value }))} className="flex-1 px-2 py-1.5 border border-gray-200 rounded-lg text-xs font-mono uppercase focus:ring-2 focus:ring-black focus:border-black outline-none w-full" />
                    </div>
                  </div>
                ))}
              </div>

              {/* Sliders */}
              {effect !== 'gradient-blobs' && (
                <>
                  <SliderControl label="Speed" value={config.speed} min={0.2} max={3} step={0.1} suffix="x" onChange={v => setConfig(c => ({ ...c, speed: v }))} />
                  {(effect === 'particles' || effect === 'starfield' || effect === 'flow-field') && (
                    <SliderControl label="Density" value={config.density} min={20} max={150} step={5} suffix="" onChange={v => setConfig(c => ({ ...c, density: v }))} />
                  )}
                  {effect === 'particles' && (
                    <SliderControl label="Connect Distance" value={config.connectDistance} min={50} max={250} step={10} suffix="px" onChange={v => setConfig(c => ({ ...c, connectDistance: v }))} />
                  )}
                </>
              )}
            </div>
          </div>
        </div>

        {/* Right column — Code Output */}
        <div className="space-y-5">

          {/* === ELEMENTOR 3-STEP GUIDE === */}
          {placement === 'container' ? (
            <>
              <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-5">
                <div className="flex items-center gap-2 mb-4">
                  <h2 className="text-sm font-semibold text-gray-900">Elementor Setup Guide</h2>
                  <span className="bg-green-600 text-[9px] text-white px-1.5 py-0.5 rounded font-bold uppercase tracking-wider">3 Steps</span>
                </div>

                <div className="space-y-4">
                  {/* STEP 1 — CSS Class */}
                  <div className="rounded-xl border border-gray-200 overflow-hidden">
                    <div className="bg-gray-50 px-4 py-2.5 flex items-center gap-2 border-b border-gray-200">
                      <span className="w-5 h-5 rounded-full bg-black text-white text-[10px] font-bold flex items-center justify-center shrink-0">1</span>
                      <span className="text-xs font-bold text-gray-800">Add CSS Class to Your Section</span>
                    </div>
                    <div className="p-4 space-y-2.5">
                      <p className="text-[11px] text-gray-500 leading-relaxed">
                        In Elementor, click your <strong>Section</strong> → <strong>Advanced</strong> tab → <strong>CSS Classes</strong> field. Paste this:
                      </p>
                      <div className="flex items-center gap-2">
                        <code className="flex-1 bg-gray-900 text-green-400 px-3 py-2 rounded-lg font-mono text-sm font-bold tracking-wide">{elementorClassName}</code>
                        <button 
                          onClick={() => handleStepCopy(elementorClassName, 'class')}
                          className={`shrink-0 px-3 py-2 rounded-lg text-xs font-bold transition-all ${copiedStep === 'class' ? 'bg-green-600 text-white' : 'bg-black text-white hover:bg-gray-800'}`}
                        >
                          {copiedStep === 'class' ? '✓ Copied' : 'Copy'}
                        </button>
                      </div>
                      <p className="text-[10px] text-gray-400 italic">This tells the script which section gets the background.</p>
                    </div>
                  </div>

                  {/* STEP 2 — Custom CSS */}
                  <div className="rounded-xl border border-gray-200 overflow-hidden">
                    <div className="bg-gray-50 px-4 py-2.5 flex items-center gap-2 border-b border-gray-200">
                      <span className="w-5 h-5 rounded-full bg-black text-white text-[10px] font-bold flex items-center justify-center shrink-0">2</span>
                      <span className="text-xs font-bold text-gray-800">Paste Custom CSS</span>
                    </div>
                    <div className="p-4 space-y-2.5">
                      <p className="text-[11px] text-gray-500 leading-relaxed">
                        Same section → <strong>Advanced</strong> tab → <strong>Custom CSS</strong> field. Paste this:
                      </p>
                      <pre className="bg-gray-900 text-gray-200 font-mono text-[10px] p-3 rounded-lg overflow-x-auto max-h-[160px] overflow-y-auto leading-relaxed whitespace-pre-wrap">{elementorCSS}</pre>
                      <button 
                        onClick={() => handleStepCopy(elementorCSS, 'css')}
                        className={`w-full py-2 rounded-lg text-xs font-bold transition-all flex items-center justify-center gap-1.5 ${copiedStep === 'css' ? 'bg-green-600 text-white' : 'bg-black text-white hover:bg-gray-800'}`}
                      >
                        {copiedStep === 'css' ? '✓ CSS Copied!' : 'Copy CSS'}
                      </button>
                      <p className="text-[10px] text-gray-400 italic">This keeps your content visible above the background canvas.</p>
                    </div>
                  </div>

                  {/* STEP 3 — Script (only for JS effects) */}
                  {!isCSSOnlyEffect && (
                    <div className="rounded-xl border border-gray-200 overflow-hidden">
                      <div className="bg-gray-50 px-4 py-2.5 flex items-center gap-2 border-b border-gray-200">
                        <span className="w-5 h-5 rounded-full bg-black text-white text-[10px] font-bold flex items-center justify-center shrink-0">3</span>
                        <span className="text-xs font-bold text-gray-800">Paste Script (One-Time)</span>
                      </div>
                      <div className="p-4 space-y-2.5">
                        <p className="text-[11px] text-gray-500 leading-relaxed">
                          Paste this <strong>once</strong> into your site. Go to:<br/>
                          <strong>WPCode Plugin</strong> → New Snippet → HTML, or<br/>
                          <strong>Elementor</strong> → Site Settings → Custom Code, or<br/>
                          <strong>Theme Settings</strong> → Header Scripts
                        </p>
                        <pre className="bg-gray-900 text-gray-200 font-mono text-[10px] p-3 rounded-lg overflow-x-auto max-h-[200px] overflow-y-auto leading-relaxed whitespace-pre-wrap">{elementorJS}</pre>
                        <button 
                          onClick={() => handleStepCopy(elementorJS, 'js')}
                          className={`w-full py-2 rounded-lg text-xs font-bold transition-all flex items-center justify-center gap-1.5 ${copiedStep === 'js' ? 'bg-green-600 text-white' : 'bg-black text-white hover:bg-gray-800'}`}
                        >
                          {copiedStep === 'js' ? '✓ Script Copied!' : 'Copy Script'}
                        </button>
                        <p className="text-[10px] text-gray-400 italic">This runs once on page load and applies the effect to ALL sections with the class above.</p>
                      </div>
                    </div>
                  )}

                  {isCSSOnlyEffect && (
                    <div className="p-3 bg-green-50 border border-green-100 rounded-lg">
                      <p className="text-[11px] text-green-800 leading-relaxed text-center font-medium">
                        🎉 This is a <strong>pure CSS effect</strong> — only 2 steps needed! No JavaScript required.
                      </p>
                    </div>
                  )}
                </div>
              </div>

              {/* How it Works */}
              <div className="bg-gray-50 rounded-xl border border-gray-200 shadow-sm p-5">
                <h3 className="text-xs font-bold text-gray-700 mb-3 uppercase tracking-wider">How It Works</h3>
                <ol className="space-y-2 text-[11px] text-gray-600 leading-relaxed">
                  <li className="flex gap-2"><span className="text-gray-400 font-mono shrink-0">1.</span> The CSS class tells the script <em>which</em> section to target</li>
                  <li className="flex gap-2"><span className="text-gray-400 font-mono shrink-0">2.</span> The Custom CSS ensures your content stays above the background</li>
                  {!isCSSOnlyEffect && <li className="flex gap-2"><span className="text-gray-400 font-mono shrink-0">3.</span> The script creates a canvas inside the section and runs the animation</li>}
                  <li className="flex gap-2"><span className="text-gray-400 font-mono shrink-0">→</span> <strong>Add the same class to multiple sections</strong> to reuse the effect!</li>
                </ol>
              </div>
            </>
          ) : (
            <>
              {/* === DEFAULT MODE — Single Code Block === */}
              <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-5 space-y-3">
                <div className="flex items-center justify-between">
                  <h2 className="text-sm font-semibold text-gray-900">Generated Code</h2>
                  <div className="flex items-center gap-2 text-[10px] text-gray-400 font-mono">
                    <span>{lineCount} lines</span>
                    <span>·</span>
                    <span>{(charCount / 1024).toFixed(1)} KB</span>
                  </div>
                </div>

                <button
                  suppressHydrationWarning
                  onClick={handleCopy}
                  className={`w-full py-3 text-sm font-semibold rounded-lg transition-all flex items-center justify-center gap-2 ${
                    copied
                      ? 'bg-green-600 text-white'
                      : 'bg-black hover:bg-gray-800 text-white'
                  }`}
                >
                  {copied ? (
                    <>
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg>
                      Copied to Clipboard!
                    </>
                  ) : (
                    <>
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg>
                      Copy Code
                    </>
                  )}
                </button>

                <p className="text-[11px] text-gray-400 text-center leading-snug">
                  {effect === 'gradient-blobs'
                    ? 'Pure HTML + CSS. Paste into any webpage.'
                    : 'Self-contained HTML + JS. Zero dependencies. Just paste it.'}
                </p>
              </div>

              {/* Toggle code view */}
              <div className="bg-gray-50 rounded-xl border border-gray-200 shadow-sm overflow-hidden">
                <button
                  suppressHydrationWarning
                  onClick={() => setCodeVisible(!codeVisible)}
                  className="w-full px-4 py-3 flex items-center justify-between text-sm font-semibold text-gray-700 hover:bg-gray-100 transition-colors"
                >
                  <span>Preview Code</span>
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={`transition-transform ${codeVisible ? 'rotate-180' : ''}`}>
                    <polyline points="6 9 12 15 18 9"></polyline>
                  </svg>
                </button>
                {codeVisible && (
                  <pre className="bg-gray-900 text-gray-100 font-mono text-[11px] p-4 overflow-x-auto whitespace-pre-wrap leading-relaxed max-h-[400px] overflow-y-auto">
                    {generatedCode}
                  </pre>
                )}
              </div>
            </>
          )}

          {/* Active colors */}
          <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-5">
            <h2 className="text-sm font-semibold text-gray-900 mb-3">Active Colors</h2>
            <div className="flex gap-2">
              {[config.colorA, config.colorB, config.colorC].map((c, i) => (
                <div key={i} className="flex-1 h-10 rounded-lg shadow-inner border border-gray-100" style={{ backgroundColor: c }} />
              ))}
            </div>
            <p className="text-[10px] text-gray-400 mt-2 font-mono text-center">
              {config.colorA} · {config.colorB} · {config.colorC}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

// ===== Reusable Slider =====
function SliderControl({ label, value, min, max, step, suffix, onChange }: {
  label: string; value: number; min: number; max: number; step: number; suffix: string;
  onChange: (v: number) => void;
}) {
  return (
    <div>
      <div className="flex justify-between items-center mb-1">
        <label className="text-xs font-medium text-gray-600">{label}</label>
        <span className="text-xs font-mono font-medium text-gray-400 bg-gray-100 px-2 py-0.5 rounded">{value}{suffix}</span>
      </div>
      <input
        suppressHydrationWarning
        type="range" min={min} max={max} step={step} value={value}
        onChange={e => onChange(parseFloat(e.target.value))}
        className="w-full h-1.5 bg-gray-200 rounded-lg appearance-none cursor-pointer accent-black"
      />
    </div>
  );
}
