'use client';
import React, { useState, useEffect } from 'react';

export default function JsonToGoStructTool() {
  const [json, setJson] = useState('{\n  "id": 1,\n  "name": "Leanne Graham",\n  "username": "Bret",\n  "email": "Sincere@april.biz",\n  "address": {\n    "street": "Kulas Light",\n    "suite": "Apt. 556",\n    "city": "Gwenborough",\n    "zipcode": "92998-3874",\n    "geo": {\n      "lat": "-37.3159",\n      "lng": "81.1496"\n    }\n  },\n  "phone": "1-770-736-8031 x56442",\n  "website": "hildegard.org",\n  "company": {\n    "name": "Romaguera-Crona",\n    "catchPhrase": "Multi-layered client-server neural-net",\n    "bs": "harness real-time e-markets"\n  }\n}');
  const [go, setGo] = useState('');
  const [isCopying, setIsCopying] = useState(false);

  // Options
  const [structName, setStructName] = useState('AutoGenerated');
  const [useJsonTags, setUseJsonTags] = useState(true);

  const formatName = (name: string) => {
    return name
      .split('_')
      .map(part => part.charAt(0).toUpperCase() + part.slice(1))
      .join('')
      .split('-')
      .map(part => part.charAt(0).toUpperCase() + part.slice(1))
      .join('');
  };

  const getType = (value: any, key: string, structs: string[]): string => {
    if (value === null) return 'interface{}';
    if (typeof value === 'number') {
      return Number.isInteger(value) ? 'int' : 'float64';
    }
    if (typeof value === 'boolean') return 'bool';
    if (typeof value === 'string') return 'string';
    if (Array.isArray(value)) {
      if (value.length === 0) return '[]interface{}';
      return `[]${getType(value[0], key, structs)}`;
    }
    if (typeof value === 'object') {
      const subStructName = formatName(key);
      generateStruct(value, subStructName, structs);
      return subStructName;
    }
    return 'interface{}';
  };

  const generateStruct = (obj: any, name: string, structs: string[]) => {
    let result = `type ${name} struct {\n`;
    Object.entries(obj).forEach(([key, value]) => {
      const titleName = formatName(key);
      const type = getType(value, key, structs);
      const jsonTag = useJsonTags ? ` \`json:"${key}"\`` : '';
      result += `\t${titleName} ${type}${jsonTag}\n`;
    });
    result += `}`;
    
    // Avoid duplicate structs if they are identical in content (basic check)
    if (!structs.some(s => s.startsWith(`type ${name} struct`))) {
        structs.push(result);
    }
  };

  const convertJsonToGo = () => {
    try {
      if (!json.trim()) {
        setGo('');
        return;
      }

      const parsed = JSON.parse(json);
      const structs: string[] = [];
      generateStruct(parsed, structName, structs);
      
      // Go is usually written with the main struct first, then sub-structs
      setGo(structs.join('\n\n'));
    } catch (err) {
      setGo('Invalid JSON input. Please ensure your format is correct.');
    }
  };

  useEffect(() => {
    convertJsonToGo();
  }, [json, structName, useJsonTags]);

  const handleCopy = () => {
    navigator.clipboard.writeText(go);
    setIsCopying(true);
    setTimeout(() => setIsCopying(false), 2000);
  };

  return (
    <div className="w-full flex flex-col gap-6">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 h-[600px]">
        
        {/* JSON Input */}
        <div className="flex flex-col gap-4">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-bold text-gray-800 uppercase tracking-widest">Input JSON</h3>
            <button onClick={() => setJson('')} className="text-xs font-bold text-red-500 hover:text-red-600">Clear</button>
          </div>
          <div className="flex-1 relative group">
            <textarea
              value={json}
              onChange={(e) => setJson(e.target.value)}
              className="w-full h-full p-6 font-mono text-sm bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none resize-none transition-all"
              placeholder='{"id": 1, "name": "Test"}'
              spellCheck="false"
            />
          </div>
        </div>

        {/* Go Output */}
        <div className="flex flex-col gap-4">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-bold text-gray-800 uppercase tracking-widest">Golang Structs</h3>
            <button
              onClick={handleCopy}
              className={`text-xs font-bold px-4 py-2 rounded-lg transition-all ${
                isCopying ? 'bg-green-100 text-green-700' : 'bg-gray-900 text-white hover:bg-gray-800'
              } flex items-center gap-2`}
            >
              {isCopying ? (
                <>
                  <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"></path></svg>
                  Copied!
                </>
              ) : (
                <>
                  <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"></path></svg>
                  Copy Go Code
                </>
              )}
            </button>
          </div>
          <div className="flex-1 relative group">
            <textarea
              readOnly
              value={go}
              className="w-full h-full p-6 font-mono text-sm bg-white border border-gray-200 rounded-xl outline-none resize-none"
              spellCheck="false"
            />
          </div>
        </div>
      </div>

      {/* Options Panel */}
      <div className="bg-white p-6 border border-gray-200 rounded-xl shadow-sm flex flex-col md:flex-row gap-8 items-center">
         <div className="flex flex-col gap-1.5 flex-1 max-w-sm">
            <span className="text-xs font-bold text-gray-400 uppercase tracking-widest">Main Struct Name</span>
            <input 
                type="text" 
                value={structName}
                onChange={(e) => setStructName(e.target.value.replace(/[^a-zA-Z0-9]/g, ''))}
                className="w-full px-4 py-2 border border-gray-200 rounded-lg text-sm font-bold focus:ring-2 focus:ring-blue-500 outline-none"
            />
         </div>

         <label className="flex items-center gap-3 cursor-pointer group">
            <div className={`w-12 h-6 flex items-center rounded-full p-1 transition-colors ${useJsonTags ? 'bg-blue-600' : 'bg-gray-300'}`}>
                <input 
                    type="checkbox" 
                    className="hidden" 
                    checked={useJsonTags} 
                    onChange={() => setUseJsonTags(!useJsonTags)} 
                />
                <div className={`bg-white w-4 h-4 rounded-full shadow-md transform transition-transform ${useJsonTags ? 'translate-x-6' : 'translate-x-0'}`} />
            </div>
            <span className="text-sm font-bold text-gray-700 group-hover:text-gray-900 transition-colors">Include JSON Tags (`json:"..."`)</span>
         </label>

         <div className="ml-auto flex gap-4 text-xs font-bold text-gray-400 uppercase tracking-widest border-l border-gray-100 pl-8">
            <div className="flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-blue-500"></span>
                Recursive Structs
            </div>
            <div className="flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-green-500"></span>
                Type Inference
            </div>
         </div>
      </div>
    </div>
  );
}
