import { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://devtoolslabs.com';

  const routes = [
    '',
    '/guides',
    '/guides/how-to-decode-jwt',
    '/guides/understanding-base64',
    '/guides/regex-explained',
    '/guides/unix-timestamps',
    '/guides/understanding-cors',
    '/guides/ultimate-curl-guide',
    '/guides/wcag-contrast-guide',
    '/guides/sql-best-practices',
    '/accessibility-tools',
    '/url-encoder',
    '/url-decoder',
    '/json-to-typescript',
    '/csp-generator',
    '/sql-to-object',
    '/yaml-to-json',
    '/json-to-yaml',
    '/http-status-codes',
    '/header-mime-hub',
    '/diagram-playground',
    '/http-header-parser',
    '/color-palette-generator',
    '/regex-generator',
    '/password-entropy',
    '/html-entity-encoder',
    '/jwt-expiry-checker',
    '/csv-to-json',
    '/json-diff',
    '/uuid-generator',
    '/json-escape-unescape',
    '/json-formatter',
    '/curl-to-fetch',
    '/query-parser',
    '/timestamp-converter',
    '/cron-parser',
    '/regex-replace',
    '/markdown-table',
    '/sql-formatter',
    '/html-minifier',
    '/css-minifier',
    '/css-clamp-generator',
    '/css-keyframes',
    '/color-contrast-checker',
    '/svg-path-visualizer',
    '/dev-utilities',
    '/json-tools',
    '/encoding-tools',
    '/frontend-tools',
    '/security-tools',
    '/privacy',
    '/terms',
  ];

  return routes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: 'weekly',
    priority: route === '' ? 1 : 0.8,
  }));
}
