import type { Metadata } from 'next';
import ToolLayout from '@/components/ToolLayout';
import SqlFormatterTool from '@/components/tools/SqlFormatterTool';

export const metadata: Metadata = {
  title: 'SQL Formatter & Beautifier (Free Online Tool) | Format Instantly',
  description: 'Instantly format and beautify messy, minified SQL queries online. Supports PostgreSQL, MySQL, SQL Server, BigQuery, and more natively in your browser.',
};

export default function SqlFormatterPage() {
  return (
    <ToolLayout
      title="SQL Formatter & Beautifier (Format SQL Queries Online)"
      intro="Are you tired of debugging massive, single-line SQL queries dumped from server logs? This tool takes minified or poorly formatted SQL and intelligently beautifies it into readable, standardized code. It understands dialect-specific syntax for all major database engines and forces consistent capitalization for SQL keywords."
      toolNode={<SqlFormatterTool />}
      howTo={[
        "Select your specific database dialect from the top dropdown (e.g., PostgreSQL, MySQL, T-SQL, BigQuery).",
        "Choose your preferred keyword capitalization (UPPERCASE is highly recommended for readability).",
        "Paste your unformatted, minified, or messy SQL query into the left text box.",
        "The right box will instantly display the cleanly structured, perfectly indented query.",
        "Click the Copy button to copy the beautified code to your clipboard."
      ]}
      examples={[
        {
          input: 'select id,name,email from users where status=\'active\' join orders on users.id=orders.user_id group by id order by created_at desc;',
          output: 'SELECT\n  id,\n  name,\n  email\nFROM\n  users\nWHERE\n  status = \'active\'\n  JOIN orders ON users.id = orders.user_id\nGROUP BY\n  id\nORDER BY\n  created_at DESC;'
        }
      ]}
      useCases={[
        "Extracting undocumented, massive single-line raw queries generated by ORMs (like Prisma or TypeORM) from backend application logs.",
        "Standardizing SQL code styling across a development team before submitting a Pull Request.",
        "Preparing complex multi-JOIN queries to be pasted into a reporting engine or dashboard like Metabase or Looker."
      ]}
      faqs={[
        {
          question: "Does this support dialect-specific features like T-SQL Server variables?",
          answer: "Yes. By selecting the correct dialect from the dropdown, the parser uses a specific Abstract Syntax Tree (AST) that understands engine-specific tokens, such as PostgreSQL's geometric operators or Microsoft SQL Server's @variables and BEGIN/END blocks."
        },
        {
          question: "Can it format multiple queries at once?",
          answer: "Absolutely. If you paste a massive SQL dump containing multiple semi-colon (;) separated statements, the formatter will process them sequentially and automatically inject two blank lines between each isolated query for maximum readability."
        },
        {
          question: "Is it safe to paste queries containing proprietary table names or PII?",
          answer: "Yes, 100% safe. This tool dynamically imports the SQL parsing engine directly into your browser's local memory. The complex AST calculations run entirely on your CPU, meaning no proprietary schema data or sensitive string literals ever touch a remote server."
        },
        {
          question: "Why does the tool sometimes throw a Syntax Error?",
          answer: "Because this is an intelligent AST parser, not a simple regex replacer. If your SQL string is missing a closing parenthesis, has a mismatched string quote, or violates core SQL structural boundaries, the parser cannot safely re-indent the code."
        },
        {
          question: "Why force UPPERCASE on SQL keywords?",
          answer: "While SQL is inherently case-insensitive, forcing reserved keywords (SELECT, FROM, WHERE, JOIN) into UPPERCASE is a universal industry standard recommended by almost all DBA style guides. It creates immediate visual distinctness from lowercase table identifiers and local variables."
        }
      ]}
      relatedTools={[
        { name: "Regex Tracker & Replacer", url: "/regex-replace" },
        { name: "JSON Escape", url: "/json-escape-unescape" }
      ]}
    />
  );
}
