import type { Metadata } from 'next';
import ToolLayout from '@/components/ToolLayout';
import UrlEncodeDecodeTool from '@/components/tools/UrlEncodeDecodeTool';

export const metadata: Metadata = {
  title: 'URL Encoder & Decoder | Percent-Encoding Tool',
  description: 'Encode special characters for safe URLs or decode percent-encoded strings locally in your browser using RFC 3986-compatible browser APIs.',
  alternates: { canonical: '/url-encode-decode' },
};

export default function UrlEncodeDecodePage() {
  return (
    <ToolLayout
      title="URL Encoder & Decoder"
      intro="Percent-encode text for safe use in URL query parameters, or decode an encoded URL component back into readable text. All conversion happens locally in your browser."
      toolNode={<UrlEncodeDecodeTool />}
      howTo={[
        "Choose Encode or Decode mode.",
        "Paste the text or URL component into the input field.",
        "Review the converted value generated by the browser's URI APIs.",
        "Copy the output into your URL, application, or test request."
      ]}
      examples={[
        { input: 'hello world@example.com', output: 'hello%20world%40example.com' }
      ]}
      useCases={[
        "Preparing query parameter values for API requests.",
        "Decoding tracking URLs during debugging.",
        "Handling spaces, emoji, and reserved characters safely in URLs."
      ]}
      faqs={[
        {
          question: "What is percent-encoding?",
          answer: "Percent-encoding represents reserved or non-ASCII characters as a percent sign followed by their UTF-8 hexadecimal bytes."
        },
        {
          question: "Is the input sent to a server?",
          answer: "No. Encoding and decoding use the browser's native URI functions on your device."
        },
        {
          question: "Why can decoding fail?",
          answer: "A malformed percent sequence, such as a percent sign without two hexadecimal digits, is not a valid encoded URL component."
        }
      ]}
      relatedTools={[
        { name: "Base64 Encoder & Decoder", url: "/base64-encode-decode" },
        { name: "HTTP Header Parser", url: "/http-header-parser" },
        { name: "Encoding Tools", url: "/encoding-tools" }
      ]}
    />
  );
}
