import type { Metadata } from 'next';
import ToolLayout from '@/components/ToolLayout';
import JsonToGoStructTool from '@/components/tools/JsonToGoStructTool';

export const metadata: Metadata = {
  title: 'JSON to Go Struct Converter | Generate Golang Types from JSON Online',
  description: 'Instantly convert JSON payloads into strongly-typed Go structs. Perfect for backend developers building Go microservices, APIs, and Kubernetes controllers. Supports recursive structs and automatic JSON tagging.',
};

export default function JsonToGoStructPage() {
  return (
    <ToolLayout
      title="JSON to Go Struct Generator (Golang Type Maker)"
      intro="For backend engineers building cloud-native applications in Go, mapping incoming JSON payloads to strongly-typed structs is a frequent, manual task. This tool automates that process by scanning your JSON structure, inferring appropriate Go types (int, float64, string, bool), and generating recursive structs with standard `json` tags. It runs 100% in your browser, keeping your API payloads private and secure."
      toolNode={<JsonToGoStructTool />}
      howTo={[
        "Paste your sample JSON object or array into the left 'Input JSON' editor.",
        "The tool instantly analyzes the keys and values to determine the hierarchy.",
        "Customize the 'Main Struct Name' to match your internal naming conventions.",
        "Ensure 'Include JSON Tags' is enabled if you plan to use standard `encoding/json` unmarshalling.",
        "The resulting Go code is displayed on the right. Click 'Copy Go Code' to use it in your project."
      ]}
      examples={[
        {
          input: '{\n  "user_id": 101,\n  "active": true,\n  "meta": { "last_login": "2026-03-15" }\n}',
          output: 'type AutoGenerated struct {\n\tUserID int `json:"user_id"`\n\tActive bool `json:"active"`\n\tMeta   Meta `json:"meta"`\n}\n\ntype Meta struct {\n\tLastLogin string `json:"last_login"`\n}'
        }
      ]}
      useCases={[
        "Quickly defining Request/Response models when building REST APIs with Gin, Fiber, or Echo.",
        "Modeling complex configuration files for Kubernetes operators or CLI tools.",
        "Deciphering large, nested JSON payloads from third-party APIs (Stripe, GitHub, etc.) into clean Go definitions.",
        "Reducing human error during manual struct definition for high-stakes production services."
      ]}
      faqs={[
        {
          question: "How does the tool handle nested objects?",
          answer: "The generator works recursively. When it encounters a nested object, it creates a new named struct type for it and appropriately references that type in the parent struct. This ensures your Go code remains modular and readable."
        },
        {
          question: "What types does it infer?",
          answer: "It maps JSON numbers to `int` if they are whole numbers, or `float64` if they contain decimals. Booleans map to `bool`, strings to `string`, and arrays to `[]type`. Null values or empty arrays are safely typed as `interface{}`."
        },
        {
          question: "Why use JSON tags in Go?",
          answer: "Go structs use PascalCase for exported fields, but JSON often uses snake_case or camelCase. The `json:\"tag\"` annotation tells the Go compiler exactly which JSON key maps to which struct field during marshalling/unmarshalling."
        },
        {
          question: "Can I use arrays of objects?",
          answer: "Yes. If you paste a JSON array containing objects, the tool will analyze the first element to determine the slice type (e.g., `[]UserStruct`)."
        },
        {
          question: "Is this tool secure for sensitive API data?",
          answer: "Absolutely. Like all DevToolsLabs utilities, the processing happens entirely on your local machine using client-side JavaScript. No data is ever transmitted to our servers."
        }
      ]}
      relatedTools={[
        { name: "JSON to TypeScript", url: "/json-to-typescript" },
        { name: "YAML to JSON Converter", url: "/yaml-to-json" },
        { name: "Mock JSON Generator", url: "/mock-json-generator" }
      ]}
    />
  );
}
