import type { Metadata } from 'next';
import ToolLayout from '@/components/ToolLayout';
import JwtValidatorTool from '@/components/tools/JwtValidatorTool';

export const metadata: Metadata = {
  title: 'JWT Decoder & Validator (Free Online Tool) | Parse Tokens Securely',
  description: 'Instantly decode JSON Web Tokens (JWT) safely in your browser. View the algorithm header and payload claims securely without sending your token to a server.',
};

export default function JwtValidatorPage() {
  return (
    <ToolLayout
      title="JWT Decoder & Validator"
      intro="JSON Web Tokens (JWT) are widely used for authentication. Paste your encoded token below to securely decode it and inspect the underlying JSON payload and header algorithms. All decoding runs entirely client-side using native JavaScript API, keeping your sensitive tokens safe."
      toolNode={<JwtValidatorTool />}
      howTo={[
        "Paste your full encoded JWT string (which consists of three parts separated by dots: header.payload.signature) into the input box.",
        "The tool will instantly parse the Base64Url encoded string.",
        "The decoded JSON Header and Payload will appear in the specific colored boxes below."
      ]}
      examples={[
        {
          input: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c',
          output: 'Header: { "alg": "HS256", "typ": "JWT" }\nPayload: { "sub": "1234567890", "name": "John Doe", "iat": 1516239022 }'
        }
      ]}
      useCases={[
        "Debugging authentication flow issues in your REST or GraphQL backend.",
        "Verifying the contents and expiration timestamp (exp claim) of an access token.",
        "Checking which hashing algorithm (e.g., RS256 or HS256) a token was signed with."
      ]}
      faqs={[
        {
          question: "How does the browser decode the JWT payload?",
          answer: "JWTs use a modified format called Base64Url encoding. Our tool dynamically converts the Base64Url format back into standard Base64 by padding it and replacing URL-safe characters (- and _), and then uses the native browser atob() function to securely decode it into readable JSON."
        },
        {
          question: "Is it safe to paste my production JWT here?",
          answer: "Yes. Unlike many server-side developer tools that log or store your input, this decoder is 100% client-side. The network tab in your browser's Developer Tools will confirm that your token never leaves your local machine."
        },
        {
          question: "Can this tool verify the signature of my token?",
          answer: "No. Signature verification requires the private key or shared secret that only your backend server possesses. This tool focuses strictly on safely decoding the public header and payload claims for debugging purposes."
        },
        {
          question: "What does the 'iat' or 'exp' claim in the payload mean?",
          answer: "Both represent Unix timestamps. 'iat' stands for 'Issued At', marking exactly when the token was generated by the server. 'exp' stands for 'Expiration Time', which is the exact moment the token becomes invalid and requires the user to re-authenticate."
        },
        {
          question: "Why does my token throw an 'Invalid JWT Format' error?",
          answer: "A valid JWT must have exactly three segments separated by two periods (header.payload.signature). If your token is missing a segment, or if you accidentally copied a trailing space or quotation mark, the decoding will fail."
        }
      ]}
      relatedTools={[
        { name: "JSON Escape", url: "/json-escape-unescape" },
        { name: "URL Query Parser", url: "/query-parser" }
      ]}
    />
  );
}
